import orderBy from 'lodash/orderBy'

export const birdsList = orderBy([
    {value: 0, text: "Accenteur alpin", link: "../oiseaux/accenteur.alpin.html"},
    {value: 1, text: "Accenteur de Radde", link: "../oiseaux/accenteur.de.radde.html"},
    {value: 2, text: "Accenteur montanelle", link: "../oiseaux/accenteur.montanelle.html"},
    {value: 3, text: "Accenteur mouchet", link: "../oiseaux/accenteur.mouchet.html"},
    {value: 4, text: "Accenteur à gorge noire", link: "../oiseaux/accenteur.a.gorge.noire.html"},
    {value: 5, text: "Agrobate roux", link: "../oiseaux/agrobate.roux.html"},
    {value: 6, text: "Aigle botté", link: "../oiseaux/aigle.botte.html"},
    {value: 7, text: "Aigle criard", link: "../oiseaux/aigle.criard.html"},
    {value: 8, text: "Aigle des steppes", link: "../oiseaux/aigle.des.steppes.html"},
    {value: 9, text: "Aigle de Bonelli", link: "../oiseaux/aigle.de.bonelli.html"},
    {value: 10, text: "Aigle ibérique", link: "../oiseaux/aigle.iberique.html"},
    {value: 11, text: "Aigle impérial", link: "../oiseaux/aigle.imperial.html"},
    {value: 12, text: "Aigle pomarin", link: "../oiseaux/aigle.pomarin.html"},
    {value: 13, text: "Aigle ravisseur", link: "../oiseaux/aigle.ravisseur.html"},
    {value: 14, text: "Aigle royal", link: "../oiseaux/aigle.royal.html"},
    {value: 15, text: "Aigrette ardoisée", link: "../oiseaux/aigrette.ardoisee.html"},
    {value: 16, text: "Aigrette bleue", link: "../oiseaux/aigrette.bleue.html"},
    {value: 17, text: "Aigrette des récifs", link: "../oiseaux/aigrette.des.recifs.html"},
    {value: 18, text: "Aigrette à gorge blanche", link: "../oiseaux/aigrette.des.recifs.html"},
    {value: 19, text: "Aigrette garzette", link: "../oiseaux/aigrette.garzette.html"},
    {value: 20, text: "Aigrette neigeuse", link: "../oiseaux/aigrette.neigeuse.html"},
    {value: 21, text: "Aigrette tricolore", link: "../oiseaux/aigrette.tricolore.html"},
    {value: 22, text: "Albatros de Tristan", link: "../oiseaux/albatros.de.tristan.html"},
    {value: 23, text: "Albatros de Tristan da Cunha", link: "../oiseaux/"},
    {value: 24, text: "Albatros hurleur", link: "../oiseaux/albatros.hurleur.html"},
    {value: 25, text: "Albatros à nez jaune", link: "../oiseaux/albatros.a.nez.jaune.html"},
    {value: 26, text: "Albatros à sourcils noirs", link: "../oiseaux/albatros.a.sourcils.noirs.html"},
    {value: 27, text: "Alouette bilophe", link: "../oiseaux/alouette.bilophe.html"},
    {value: 28, text: "Alouette calandre", link: "../oiseaux/alouette.calandre.html"},
    {value: 29, text: "Alouette calandrelle", link: "../oiseaux/alouette.calandrelle.html"},
    {value: 30, text: "Alouette des champs", link: "../oiseaux/alouette.des.champs.html"},
    {value: 31, text: "Alouette de Clot-Bey", link: "../oiseaux/alouette.de.clot-bey.html"},
    {value: 32, text: "Alouette de Swinhoe", link: "../oiseaux/alouette.de.swinhoe.html"},
    {value: 33, text: "Alouette gulgule", link: "../oiseaux/alouette.gulgule.html"},
    {value: 34, text: "Alouette haussecol", link: "../oiseaux/alouette.haussecol.html"},
    {value: 35, text: "Alouette hausse-col", link: "../oiseaux/alouette.haussecol.html"},
    {value: 36, text: "Alouette leucoptère", link: "../oiseaux/alouette.leucoptere.html"},
    {value: 37, text: "Alouette lulu", link: "../oiseaux/alouette.lulu.html"},
    {value: 38, text: "Alouette monticole", link: "../oiseaux/alouette.monticole.html"},
    {value: 39, text: "Alouette nègre", link: "../oiseaux/alouette.negre.html"},
    {value: 40, text: "Alouette pispolette", link: "../oiseaux/alouette.pispolette.html"},
    {value: 41, text: "Amadine cou-coupé", link: "../oiseaux/amadine.cou-coupe.html"},
    {value: 42, text: "Ammomane isabelline", link: "../oiseaux/ammomane.isabelline.html"},
    {value: 43, text: "Ammomane élégante", link: "../oiseaux/ammomane.elegante.html"},
    {value: 44, text: "Anhinga d'Afrique", link: "../oiseaux/anhinga.d.afrique.html"},
    {value: 45, text: "Arlequin plongeur", link: "../oiseaux/arlequin.plongeur.html"},
    {value: 46, text: "Astrild cendré", link: "../oiseaux/astrild.cendre.html"},
    {value: 47, text: "Astrild ondulé", link: "../oiseaux/astrild.ondule.html"},
    {value: 48, text: "Astrild à joues orange", link: "../oiseaux/astrild.a.joues.orange.html"},
    {value: 49, text: "Autour des palombes", link: "../oiseaux/autour.des.palombes.html"},
    {value: 50, text: "Avocette d'Amérique", link: "../oiseaux/avocette.d.amerique.html"},
    {value: 51, text: "Avocette élégante", link: "../oiseaux/avocette.elegante.html"},
    {value: 52, text: "Balbuzard pêcheur", link: "../oiseaux/balbuzard.pecheur.html"},
    {value: 53, text: "Barge hudsonienne", link: "../oiseaux/barge.hudsonienne.html"},
    {value: 54, text: "Barge rousse", link: "../oiseaux/barge.rousse.html"},
    {value: 55, text: "Barge à queue noire", link: "../oiseaux/barge.a.queue.noire.html"},
    {value: 56, text: "Bartramie des champs", link: "../oiseaux/bartramie.des.champs.html"},
    {value: 57, text: "Maubèche des champs", link: "../oiseaux/bartramie.des.champs.html"},
    {value: 58, text: "Bateleur des savanes", link: "../oiseaux/bateleur.des.savanes.html"},
    {value: 59, text: "Bec-croisé bifascié", link: "../oiseaux/bec-croise.bifascie.html"},
    {value: 60, text: "Bec-croisé d'Ecosse", link: "../oiseaux/bec-croise.d.ecosse.html"},
    {value: 61, text: "Bec-croisé d'Écosse", link: "../oiseaux/"},
    {value: 62, text: "Bec-croisé des sapins", link: "../oiseaux/bec-croise.des.sapins.html"},
    {value: 63, text: "Bec-croisé perroquet", link: "../oiseaux/bec-croise.perroquet.html"},
    {value: 64, text: "Bec-en-ciseaux noir", link: "../oiseaux/bec-en-ciseaux.noir.html"},
    {value: 65, text: "Bengali rouge", link: "../oiseaux/bengali.rouge.html"},
    {value: 66, text: "Bergeronnette citrine", link: "../oiseaux/bergeronnette.citrine.html"},
    {value: 67, text: "Bergeronnette des ruisseaux", link: "../oiseaux/bergeronnette.des.ruisseaux.html"},
    {value: 68, text: "Bergeronnette de Béringie", link: "../oiseaux/bergeronnette.de.beringie.html"},
    {value: 69, text: "Bergeronnette grise", link: "../oiseaux/bergeronnette.grise.html"},
    {value: 70, text: "Bergeronnette printanière", link: "../oiseaux/bergeronnette.printaniere.html"},
    {value: 71, text: "Bernache cravant", link: "../oiseaux/bernache.cravant.html"},
    {value: 72, text: "Bernache de Hutchins", link: "../oiseaux/bernache.de.hutchins.html"},
    {value: 73, text: "Bernache du Canada", link: "../oiseaux/bernache.du.canada.html"},
    {value: 74, text: "Bernache nonnette", link: "../oiseaux/bernache.nonnette.html"},
    {value: 75, text: "Bernache à cou roux", link: "../oiseaux/bernache.a.cou.roux.html"},
    {value: 76, text: "Bihoreau gris", link: "../oiseaux/bihoreau.gris.html"},
    {value: 77, text: "Bihoreau violacé", link: "../oiseaux/bihoreau.violace.html"},
    {value: 78, text: "Blongios de Sturm", link: "../oiseaux/blongios.de.sturm.html"},
    {value: 79, text: "Blongios mandchou", link: "../oiseaux/blongios.mandchou.html"},
    {value: 80, text: "Blongios de Schrenck", link: "../oiseaux/blongios.mandchou.html"},
    {value: 81, text: "Blongios nain", link: "../oiseaux/blongios.nain.html"},
    {value: 82, text: "Bondrée apivore", link: "../oiseaux/bondree.apivore.html"},
    {value: 83, text: "Bondrée orientale", link: "../oiseaux/bondree.orientale.html"},
    {value: 84, text: "Bouscarle de Cetti", link: "../oiseaux/bouscarle.de.cetti.html"},
    {value: 85, text: "Bouvreuil des Açores", link: "../oiseaux/bouvreuil.des.acores.html"},
    {value: 86, text: "Bouvreuil pivoine", link: "../oiseaux/bouvreuil.pivoine.html"},
    {value: 87, text: "Bruant ardoisé", link: "../oiseaux/bruant.ardoise.html"},
    {value: 88, text: "Bruant auréole", link: "../oiseaux/bruant.aureole.html"},
    {value: 89, text: "Bruant cendrillard", link: "../oiseaux/bruant.cendrillard.html"},
    {value: 90, text: "Bruant cendré", link: "../oiseaux/bruant.cendre.html"},
    {value: 91, text: "Bruant chanteur", link: "../oiseaux/bruant.chanteur.html"},
    {value: 92, text: "Bruant des neiges", link: "../oiseaux/bruant.des.neiges.html"},
    {value: 93, text: "Plectrophane des neiges", link: "../oiseaux/bruant.des.neiges.html"},
    {value: 94, text: "Bruant des prés", link: "../oiseaux/bruant.des.pres.html"},
    {value: 95, text: "Bruant des roseaux", link: "../oiseaux/bruant.des.roseaux.html"},
    {value: 96, text: "Bruant de Lincoln", link: "../oiseaux/bruant.de.lincoln.html"},
    {value: 97, text: "Bruant de Pallas", link: "../oiseaux/bruant.de.pallas.html"},
    {value: 98, text: "Bruant du Sahara", link: "../oiseaux/bruant.du.sahara.html"},
    {value: 99, text: "Bruant fauve", link: "../oiseaux/bruant.fauve.html"},
    {value: 100, text: "Bruant fou", link: "../oiseaux/bruant.fou.html"},
    {value: 101, text: "Bruant fuligineux", link: "../oiseaux/bruant.fuligineux.html"},
    {value: 102, text: "Bruant hudsonien", link: "../oiseaux/bruant.hudsonien.html"},
    {value: 103, text: "Bruant jaune", link: "../oiseaux/bruant.jaune.html"},
    {value: 104, text: "Bruant lapon", link: "../oiseaux/bruant.lapon.html"},
    {value: 105, text: "Plectrophane lapon", link: "../oiseaux/bruant.lapon.html"},
    {value: 106, text: "Bruant masqué", link: "../oiseaux/bruant.masque.html"},
    {value: 107, text: "Bruant mélanocéphale", link: "../oiseaux/bruant.melanocephale.html"},
    {value: 108, text: "Bruant nain", link: "../oiseaux/bruant.nain.html"},
    {value: 109, text: "Bruant ortolan", link: "../oiseaux/bruant.ortolan.html"},
    {value: 110, text: "Bruant proyer", link: "../oiseaux/bruant.proyer.html"},
    {value: 111, text: "Bruant roux", link: "../oiseaux/bruant.roux.html"},
    {value: 112, text: "Bruant rustique", link: "../oiseaux/bruant.rustique.html"},
    {value: 113, text: "Bruant striolé", link: "../oiseaux/bruant.striole.html"},
    {value: 114, text: "Bruant zizi", link: "../oiseaux/bruant.zizi.html"},
    {value: 115, text: "Bruant à calotte blanche", link: "../oiseaux/bruant.a.calotte.blanche.html"},
    {value: 116, text: "Bruant à couronne blanche", link: "../oiseaux/bruant.a.couronne.blanche.html"},
    {value: 117, text: "Bruant à cou gris", link: "../oiseaux/bruant.a.cou.gris.html"},
    {value: 118, text: "Bruant à gorge blanche", link: "../oiseaux/bruant.a.gorge.blanche.html"},
    {value: 119, text: "Bruant à joues marron", link: "../oiseaux/bruant.a.joues.marron.html"},
    {value: 120, text: "Bruant à oreillons", link: "../oiseaux/bruant.a.oreillons.html"},
    {value: 121, text: "Bruant à sourcils jaunes", link: "../oiseaux/bruant.a.sourcils.jaunes.html"},
    {value: 122, text: "Bruant à tête rousse", link: "../oiseaux/bruant.a.tete.rousse.html"},
    {value: 123, text: "Bulbul des jardins", link: "../oiseaux/bulbul.des.jardins.html"},
    {value: 124, text: "Bulbul orphée", link: "../oiseaux/bulbul.orphee.html"},
    {value: 125, text: "Bulbul à oreillons blancs", link: "../oiseaux/bulbul.a.oreillons.blancs.html"},
    {value: 126, text: "Busard cendré", link: "../oiseaux/busard.cendre.html"},
    {value: 127, text: "Busard d'Amérique", link: "../oiseaux/busard.d.amerique.html"},
    {value: 128, text: "Busard des marais", link: "../oiseaux/busard.d.amerique.html"},
    {value: 129, text: "Busard des roseaux", link: "../oiseaux/busard.des.roseaux.html"},
    {value: 130, text: "Busard pâle", link: "../oiseaux/busard.pale.html"},
    {value: 131, text: "Busard Saint-Martin", link: "../oiseaux/busard.saint-martin.html"},
    {value: 132, text: "Buse de Chine", link: "../oiseaux/buse.de.chine.html"},
    {value: 133, text: "Buse de Swainson", link: "../oiseaux/buse.de.swainson.html"},
    {value: 134, text: "Buse féroce", link: "../oiseaux/buse.feroce.html"},
    {value: 135, text: "Buse pattue", link: "../oiseaux/buse.pattue.html"},
    {value: 136, text: "Buse variable", link: "../oiseaux/buse.variable.html"},
    {value: 137, text: "Butor d'Amérique", link: "../oiseaux/butor.d.amerique.html"},
    {value: 138, text: "Butor étoilé", link: "../oiseaux/butor.etoile.html"},
    {value: 139, text: "Bécasseau cocorli", link: "../oiseaux/becasseau.cocorli.html"},
    {value: 140, text: "Bécasseau d'Alaska", link: "../oiseaux/becasseau.d.alaska.html"},
    {value: 141, text: "Bécasseau de Baird", link: "../oiseaux/becasseau.de.baird.html"},
    {value: 142, text: "Bécasseau de Bonaparte", link: "../oiseaux/becasseau.de.bonaparte.html"},
    {value: 143, text: "Bécasseau à croupion blanc", link: "../oiseaux/becasseau.de.bonaparte.html"},
    {value: 144, text: "Bécasseau de l'Anadyr", link: "../oiseaux/becasseau.de.l.anadyr.html"},
    {value: 145, text: "Bécasseau de Temminck", link: "../oiseaux/becasseau.de.temminck.html"},
    {value: 146, text: "Bécasseau falcinelle", link: "../oiseaux/becasseau.falcinelle.html"},
    {value: 147, text: "Bécasseau maubèche", link: "../oiseaux/becasseau.maubeche.html"},
    {value: 148, text: "Bécasseau minuscule", link: "../oiseaux/becasseau.minuscule.html"},
    {value: 149, text: "Bécasseau minute", link: "../oiseaux/becasseau.minute.html"},
    {value: 150, text: "Bécasseau rousset", link: "../oiseaux/becasseau.rousset.html"},
    {value: 151, text: "Bécasseau roussâtre", link: "../oiseaux/becasseau.rousset.html"},
    {value: 152, text: "Bécasseau sanderling", link: "../oiseaux/becasseau.sanderling.html"},
    {value: 153, text: "Bécasseau semipalmé", link: "../oiseaux/becasseau.semipalme.html"},
    {value: 154, text: "Bécasseau spatule", link: "../oiseaux/becasseau.spatule.html"},
    {value: 155, text: "Bécasseau tacheté", link: "../oiseaux/becasseau.tachete.html"},
    {value: 156, text: "Bécasseau à poitrine cendrée", link: "../oiseaux/becasseau.tachete.html"},
    {value: 157, text: "Bécasseau variable", link: "../oiseaux/becasseau.variable.html"},
    {value: 158, text: "Bécasseau violet", link: "../oiseaux/becasseau.violet.html"},
    {value: 159, text: "Bécasseau à cou roux", link: "../oiseaux/becasseau.a.cou.roux.html"},
    {value: 160, text: "Bécasseau à col roux", link: "../oiseaux/becasseau.a.cou.roux.html"},
    {value: 161, text: "Bécasseau à longs doigts", link: "../oiseaux/becasseau.a.longs.doigts.html"},
    {value: 162, text: "Bécasseau à queue pointue", link: "../oiseaux/becasseau.a.queue.pointue.html"},
    {value: 163, text: "Bécasseau à échasses", link: "../oiseaux/becasseau.a.echasses.html"},
    {value: 164, text: "Bécasse d'Amérique", link: "../oiseaux/becasse.d.amerique.html"},
    {value: 165, text: "Bécasse des bois", link: "../oiseaux/becasse.des.bois.html"},
    {value: 166, text: "Bécassine des marais", link: "../oiseaux/becassine.des.marais.html"},
    {value: 167, text: "Bécassine de Swinhoe", link: "../oiseaux/becassine.de.swinhoe.html"},
    {value: 168, text: "Bécassine de Wilson", link: "../oiseaux/becassine.de.wilson.html"},
    {value: 169, text: "Bécassine double", link: "../oiseaux/becassine.double.html"},
    {value: 170, text: "Bécassine sourde", link: "../oiseaux/becassine.sourde.html"},
    {value: 171, text: "Bécassine à queue pointue", link: "../oiseaux/becassine.a.queue.pointue.html"},
    {value: 172, text: "Bécassin à bec court", link: "../oiseaux/becassin.a.bec.court.html"},
    {value: 173, text: "Bécassin roux", link: "../oiseaux/becassin.a.bec.court.html"},
    {value: 174, text: "Bécassin à long bec", link: "../oiseaux/becassin.a.long.bec.html"},
    {value: 175, text: "Caille des blés", link: "../oiseaux/caille.des.bles.html"},
    {value: 176, text: "Caille du Japon", link: "../oiseaux/caille.du.japon.html"},
    {value: 177, text: "Canard carolin", link: "../oiseaux/canard.carolin.html"},
    {value: 178, text: "Canard branchu", link: "../oiseaux/canard.carolin.html"},
    {value: 179, text: "Canard chipeau", link: "../oiseaux/canard.chipeau.html"},
    {value: 180, text: "Canard colvert", link: "../oiseaux/canard.colvert.html"},
    {value: 181, text: "Canard du Cap", link: "../oiseaux/canard.du.cap.html"},
    {value: 182, text: "Canard mandarin", link: "../oiseaux/canard.mandarin.html"},
    {value: 183, text: "Canard musqué", link: "../oiseaux/canard.musque.html"},
    {value: 184, text: "Canard noir", link: "../oiseaux/canard.noir.html"},
    {value: 185, text: "Canard pilet", link: "../oiseaux/canard.pilet.html"},
    {value: 186, text: "Canard siffleur", link: "../oiseaux/canard.siffleur.html"},
    {value: 187, text: "Canard souchet", link: "../oiseaux/canard.souchet.html"},
    {value: 188, text: "Canard à faucilles", link: "../oiseaux/canard.a.faucilles.html"},
    {value: 189, text: "Canard à front blanc", link: "../oiseaux/canard.a.front.blanc.html"},
    {value: 190, text: "Canard d'Amérique", link: "../oiseaux/canard.a.front.blanc.html"},
    {value: 191, text: "Capucin bec-d'argent", link: "../oiseaux/capucin.bec-d.argent.html"},
    {value: 192, text: "Capucin bec-de-plomb", link: "../oiseaux/capucin.bec-de-plomb.html"},
    {value: 193, text: "Capucin damier", link: "../oiseaux/capucin.damier.html"},
    {value: 194, text: "Capucin à dos marron", link: "../oiseaux/capucin.a.dos.marron.html"},
    {value: 195, text: "Capucin à tête noire", link: "../oiseaux/capucin.a.tete.noire.html"},
    {value: 196, text: "Cardinal à poitrine rose", link: "../oiseaux/cardinal.a.poitrine.rose.html"},
    {value: 197, text: "Carouge à tête jaune", link: "../oiseaux/carouge.a.tete.jaune.html"},
    {value: 198, text: "Carouge à épaulettes", link: "../oiseaux/carouge.a.epaulettes.html"},
    {value: 199, text: "Cassenoix moucheté", link: "../oiseaux/cassenoix.mouchete.html"},
    {value: 200, text: "Chardonneret élégant", link: "../oiseaux/chardonneret.elegant.html"},
    {value: 201, text: "Chevalier aboyeur", link: "../oiseaux/chevalier.aboyeur.html"},
    {value: 202, text: "Chevalier arlequin", link: "../oiseaux/chevalier.arlequin.html"},
    {value: 203, text: "Chevalier bargette", link: "../oiseaux/chevalier.bargette.html"},
    {value: 204, text: "Chevalier criard", link: "../oiseaux/chevalier.criard.html"},
    {value: 205, text: "Grand Chevalier", link: "../oiseaux/"},
    {value: 206, text: "Chevalier culblanc", link: "../oiseaux/chevalier.culblanc.html"},
    {value: 207, text: "Chevalier cul-blanc", link: "../oiseaux/chevalier.culblanc.html"},
    {value: 208, text: "Chevalier de Sibérie", link: "../oiseaux/chevalier.de.siberie.html"},
    {value: 209, text: "Chevalier gambette", link: "../oiseaux/chevalier.gambette.html"},
    {value: 210, text: "Chevalier grivelé", link: "../oiseaux/chevalier.grivele.html"},
    {value: 211, text: "Chevalier guignette", link: "../oiseaux/chevalier.guignette.html"},
    {value: 212, text: "Chevalier semipalmé", link: "../oiseaux/chevalier.semipalme.html"},
    {value: 213, text: "Chevalier solitaire", link: "../oiseaux/chevalier.solitaire.html"},
    {value: 214, text: "Chevalier stagnatile", link: "../oiseaux/chevalier.stagnatile.html"},
    {value: 215, text: "Chevalier sylvain", link: "../oiseaux/chevalier.sylvain.html"},
    {value: 216, text: "Chevalier à pattes jaunes", link: "../oiseaux/chevalier.a.pattes.jaunes.html"},
    {value: 217, text: "Petit Chevalier", link: "../oiseaux/"},
    {value: 218, text: "Chevêchette d'Europe", link: "../oiseaux/chevechette.d.europe.html"},
    {value: 219, text: "Chevêche d'Athéna", link: "../oiseaux/cheveche.d.athena.html"},
    {value: 220, text: "Chionis blanc", link: "../oiseaux/chionis.blanc.html"},
    {value: 221, text: "Chocard à bec jaune", link: "../oiseaux/chocard.a.bec.jaune.html"},
    {value: 222, text: "Choucador à oreillons bleus", link: "../oiseaux/choucador.a.oreillons.bleus.html"},
    {value: 223, text: "Choucas des tours", link: "../oiseaux/choucas.des.tours.html"},
    {value: 224, text: "Choucas de Daourie", link: "../oiseaux/choucas.de.daourie.html"},
    {value: 225, text: "Chouette de l'Oural", link: "../oiseaux/chouette.de.l.oural.html"},
    {value: 226, text: "Chouette de Tengmalm", link: "../oiseaux/chouette.de.tengmalm.html"},
    {value: 227, text: "Nyctale de Tengmalm", link: "../oiseaux/chouette.de.tengmalm.html"},
    {value: 228, text: "Chouette hulotte", link: "../oiseaux/chouette.hulotte.html"},
    {value: 229, text: "Chouette hulotte africaine", link: "../oiseaux/chouette.hulotte.africaine.html"},
    {value: 230, text: "Chouette hulotte (mauritanica)", link: "../oiseaux/"},
    {value: 231, text: "Chouette lapone", link: "../oiseaux/chouette.lapone.html"},
    {value: 232, text: "Chouette épervière", link: "../oiseaux/chouette.eperviere.html"},
    {value: 233, text: "Épervière boréale", link: "../oiseaux/chouette.eperviere.html"},
    {value: 234, text: "Cigogne blanche", link: "../oiseaux/cigogne.blanche.html"},
    {value: 235, text: "Cigogne noire", link: "../oiseaux/cigogne.noire.html"},
    {value: 236, text: "Cincle plongeur", link: "../oiseaux/cincle.plongeur.html"},
    {value: 237, text: "Circaète Jean-le-Blanc", link: "../oiseaux/circaete.jean-le-blanc.html"},
    {value: 238, text: "Cisticole des joncs", link: "../oiseaux/cisticole.des.joncs.html"},
    {value: 239, text: "Cochevis de Thékla", link: "../oiseaux/cochevis.de.thekla.html"},
    {value: 240, text: "Cochevis huppé", link: "../oiseaux/cochevis.huppe.html"},
    {value: 241, text: "Colin de Californie", link: "../oiseaux/colin.de.californie.html"},
    {value: 242, text: "Colin de Virginie", link: "../oiseaux/colin.de.virginie.html"},
    {value: 243, text: "Combattant varié", link: "../oiseaux/combattant.varie.html"},
    {value: 244, text: "Conure à tête rouge", link: "../oiseaux/conure.a.tete.rouge.html"},
    {value: 245, text: "Corbeau brun", link: "../oiseaux/corbeau.brun.html"},
    {value: 246, text: "Corbeau familier", link: "../oiseaux/corbeau.familier.html"},
    {value: 247, text: "Corbeau freux", link: "../oiseaux/corbeau.freux.html"},
    {value: 248, text: "Corbeau pie", link: "../oiseaux/corbeau.pie.html"},
    {value: 249, text: "Corbeau à queue courte", link: "../oiseaux/corbeau.a.queue.courte.html"},
    {value: 250, text: "Cormoran africain", link: "../oiseaux/cormoran.africain.html"},
    {value: 251, text: "Cormoran huppé", link: "../oiseaux/cormoran.huppe.html"},
    {value: 252, text: "Cormoran pygmée", link: "../oiseaux/cormoran.pygmee.html"},
    {value: 253, text: "Cormoran à aigrettes", link: "../oiseaux/cormoran.a.aigrettes.html"},
    {value: 254, text: "Cormoran à poitrine blanche", link: "../oiseaux/cormoran.a.poitrine.blanche.html"},
    {value: 255, text: "Corneille mantelée", link: "../oiseaux/corneille.mantelee.html"},
    {value: 256, text: "Corneille noire", link: "../oiseaux/corneille.noire.html"},
    {value: 257, text: "Coucou de Chine", link: "../oiseaux/coucou.de.chine.html"},
    {value: 258, text: "Coucou de l'Himalaya", link: "../oiseaux/coucou.de.l.himalaya.html"},
    {value: 259, text: "Coucou geai", link: "../oiseaux/coucou.geai.html"},
    {value: 260, text: "Coucou gris", link: "../oiseaux/coucou.gris.html"},
    {value: 261, text: "Coucou oriental", link: "../oiseaux/coucou.oriental.html"},
    {value: 262, text: "Coulicou à bec jaune", link: "../oiseaux/coulicou.a.bec.jaune.html"},
    {value: 263, text: "Coulicou à bec noir", link: "../oiseaux/coulicou.a.bec.noir.html"},
    {value: 264, text: "Courlis cendré", link: "../oiseaux/courlis.cendre.html"},
    {value: 265, text: "Courlis corlieu", link: "../oiseaux/courlis.corlieu.html"},
    {value: 266, text: "Courlis esquimau", link: "../oiseaux/courlis.esquimau.html"},
    {value: 267, text: "Courlis hudsonien", link: "../oiseaux/courlis.hudsonien.html"},
    {value: 268, text: "Courlis nain", link: "../oiseaux/courlis.nain.html"},
    {value: 269, text: "Courlis à bec grêle", link: "../oiseaux/courlis.a.bec.grele.html"},
    {value: 270, text: "Courvite isabelle", link: "../oiseaux/courvite.isabelle.html"},
    {value: 271, text: "Crabier chevelu", link: "../oiseaux/crabier.chevelu.html"},
    {value: 272, text: "Crabier chinois", link: "../oiseaux/crabier.chinois.html"},
    {value: 273, text: "Crabier de Gray", link: "../oiseaux/crabier.de.gray.html"},
    {value: 274, text: "Crave à bec rouge", link: "../oiseaux/crave.a.bec.rouge.html"},
    {value: 275, text: "Crécerelle d'Amérique", link: "../oiseaux/crecerelle.d.amerique.html"},
    {value: 276, text: "Cygne chanteur", link: "../oiseaux/cygne.chanteur.html"},
    {value: 277, text: "Cygne de Bewick", link: "../oiseaux/cygne.de.bewick.html"},
    {value: 278, text: "Cygne siffleur", link: "../oiseaux/cygne.de.bewick.html"},
    {value: 279, text: "Cygne noir", link: "../oiseaux/cygne.noir.html"},
    {value: 280, text: "Cygne tuberculé", link: "../oiseaux/cygne.tubercule.html"},
    {value: 281, text: "Damier du Cap", link: "../oiseaux/damier.du.cap.html"},
    {value: 282, text: "Dendrocygne fauve", link: "../oiseaux/dendrocygne.fauve.html"},
    {value: 283, text: "Dendrocygne veuf", link: "../oiseaux/dendrocygne.veuf.html"},
    {value: 284, text: "Diamant mandarin", link: "../oiseaux/diamant.mandarin.html"},
    {value: 285, text: "Dickcissel d'Amérique", link: "../oiseaux/dickcissel.d.amerique.html"},
    {value: 286, text: "Durbec des sapins", link: "../oiseaux/durbec.des.sapins.html"},
    {value: 287, text: "Effraie d'Amérique", link: "../oiseaux/effraie.d.amerique.html"},
    {value: 288, text: "Effraie des clochers", link: "../oiseaux/effraie.des.clochers.html"},
    {value: 289, text: "Chouette effraie", link: "../oiseaux/effraie.des.clochers.html"},
    {value: 290, text: "Eider de Steller", link: "../oiseaux/eider.de.steller.html"},
    {value: 291, text: "Eider à duvet", link: "../oiseaux/eider.a.duvet.html"},
    {value: 292, text: "Eider à lunettes", link: "../oiseaux/eider.a.lunettes.html"},
    {value: 293, text: "Eider à tête grise", link: "../oiseaux/eider.a.tete.grise.html"},
    {value: 294, text: "Engoulevent d'Amérique", link: "../oiseaux/engoulevent.d.amerique.html"},
    {value: 295, text: "Engoulevent d'Europe", link: "../oiseaux/engoulevent.d.europe.html"},
    {value: 296, text: "Engoulevent du désert", link: "../oiseaux/engoulevent.du.desert.html"},
    {value: 297, text: "Engoulevent à collier roux", link: "../oiseaux/engoulevent.a.collier.roux.html"},
    {value: 298, text: "Euplecte vorabé", link: "../oiseaux/euplecte.vorabe.html"},
    {value: 299, text: "Faisan de Colchide", link: "../oiseaux/faisan.de.colchide.html"},
    {value: 300, text: "Faisan de Lady Amherst", link: "../oiseaux/faisan.de.lady.amherst.html"},
    {value: 301, text: "Faisan doré", link: "../oiseaux/faisan.dore.html"},
    {value: 302, text: "Faisan vénéré", link: "../oiseaux/faisan.venere.html"},
    {value: 303, text: "Faucon concolore", link: "../oiseaux/faucon.concolore.html"},
    {value: 304, text: "Faucon crécerelle", link: "../oiseaux/faucon.crecerelle.html"},
    {value: 305, text: "Faucon crécerellette", link: "../oiseaux/faucon.crecerellette.html"},
    {value: 306, text: "Faucon d'Éléonore", link: "../oiseaux/faucon.d.eleonore.html"},
    {value: 307, text: "Faucon de l'Amour", link: "../oiseaux/faucon.de.l.amour.html"},
    {value: 308, text: "Faucon gerfaut", link: "../oiseaux/faucon.gerfaut.html"},
    {value: 309, text: "Faucon hobereau", link: "../oiseaux/faucon.hobereau.html"},
    {value: 310, text: "Faucon kobez", link: "../oiseaux/faucon.kobez.html"},
    {value: 311, text: "Faucon lanier", link: "../oiseaux/faucon.lanier.html"},
    {value: 312, text: "Faucon pèlerin", link: "../oiseaux/faucon.pelerin.html"},
    {value: 313, text: "Faucon sacre", link: "../oiseaux/faucon.sacre.html"},
    {value: 314, text: "Faucon émerillon", link: "../oiseaux/faucon.emerillon.html"},
    {value: 315, text: "Fauvette babillarde", link: "../oiseaux/fauvette.babillarde.html"},
    {value: 316, text: "Fauvette des Balkans", link: "../oiseaux/fauvette.des.balkans.html"},
    {value: 317, text: "Fauvette des Baléares", link: "../oiseaux/fauvette.des.baleares.html"},
    {value: 318, text: "Fauvette des jardins", link: "../oiseaux/fauvette.des.jardins.html"},
    {value: 319, text: "Fauvette de Chypre", link: "../oiseaux/fauvette.de.chypre.html"},
    {value: 320, text: "Fauvette de Hume", link: "../oiseaux/fauvette.de.hume.html"},
    {value: 321, text: "Fauvette de l'Atlas", link: "../oiseaux/fauvette.de.l.atlas.html"},
    {value: 322, text: "Fauvette de Moltoni", link: "../oiseaux/fauvette.de.moltoni.html"},
    {value: 323, text: "Fauvette de Ménétries", link: "../oiseaux/fauvette.de.menetries.html"},
    {value: 324, text: "Fauvette de Rüppell", link: "../oiseaux/fauvette.de.ruppell.html"},
    {value: 325, text: "Fauvette du désert", link: "../oiseaux/fauvette.du.desert.html"},
    {value: 326, text: "Fauvette grisette", link: "../oiseaux/fauvette.grisette.html"},
    {value: 327, text: "Fauvette minule", link: "../oiseaux/fauvette.minule.html"},
    {value: 328, text: "Fauvette mélanocéphale", link: "../oiseaux/fauvette.melanocephale.html"},
    {value: 329, text: "Fauvette naine", link: "../oiseaux/fauvette.naine.html"},
    {value: 330, text: "Fauvette orphéane", link: "../oiseaux/fauvette.orpheane.html"},
    {value: 331, text: "Fauvette orphée", link: "../oiseaux/fauvette.orphee.html"},
    {value: 332, text: "Fauvette passerinette", link: "../oiseaux/fauvette.passerinette.html"},
    {value: 333, text: "Fauvette pitchou", link: "../oiseaux/fauvette.pitchou.html"},
    {value: 334, text: "Fauvette sarde", link: "../oiseaux/fauvette.sarde.html"},
    {value: 335, text: "Fauvette à lunettes", link: "../oiseaux/fauvette.a.lunettes.html"},
    {value: 336, text: "Fauvette à tête noire", link: "../oiseaux/fauvette.a.tete.noire.html"},
    {value: 337, text: "Fauvette épervière", link: "../oiseaux/fauvette.eperviere.html"},
    {value: 338, text: "Flamant des Caraïbes", link: "../oiseaux/flamant.des.caraibes.html"},
    {value: 339, text: "Flamant du Chili", link: "../oiseaux/flamant.du.chili.html"},
    {value: 340, text: "Flamant nain", link: "../oiseaux/flamant.nain.html"},
    {value: 341, text: "Flamant rose", link: "../oiseaux/flamant.rose.html"},
    {value: 342, text: "Foulque caronculée", link: "../oiseaux/foulque.caronculee.html"},
    {value: 343, text: "Foulque à crête", link: "../oiseaux/foulque.caronculee.html"},
    {value: 344, text: "Foulque d'Amérique", link: "../oiseaux/foulque.d.amerique.html"},
    {value: 345, text: "Foulque macroule", link: "../oiseaux/foulque.macroule.html"},
    {value: 346, text: "Fou brun", link: "../oiseaux/fou.brun.html"},
    {value: 347, text: "Fou de Bassan", link: "../oiseaux/fou.de.bassan.html"},
    {value: 348, text: "Fou du Cap", link: "../oiseaux/fou.du.cap.html"},
    {value: 349, text: "Fou masqué", link: "../oiseaux/fou.masque.html"},
    {value: 350, text: "Fou à pieds rouges", link: "../oiseaux/fou.a.pieds.rouges.html"},
    {value: 351, text: "Francolin d'Erckel", link: "../oiseaux/francolin.d.erckel.html"},
    {value: 352, text: "Francolin noir", link: "../oiseaux/francolin.noir.html"},
    {value: 353, text: "Frégate aigle-de-mer", link: "../oiseaux/fregate.aigle-de-mer.html"},
    {value: 354, text: "Frégate superbe", link: "../oiseaux/fregate.superbe.html"},
    {value: 355, text: "Fuligule milouin", link: "../oiseaux/fuligule.milouin.html"},
    {value: 356, text: "Fuligule milouinan", link: "../oiseaux/fuligule.milouinan.html"},
    {value: 357, text: "Fuligule morillon", link: "../oiseaux/fuligule.morillon.html"},
    {value: 358, text: "Fuligule nyroca", link: "../oiseaux/fuligule.nyroca.html"},
    {value: 359, text: "Fuligule à bec cerclé", link: "../oiseaux/fuligule.a.bec.cercle.html"},
    {value: 360, text: "Fuligule à collier", link: "../oiseaux/"},
    {value: 361, text: "Fuligule à dos blanc", link: "../oiseaux/fuligule.a.dos.blanc.html"},
    {value: 362, text: "Fuligule à tête noire", link: "../oiseaux/fuligule.a.tete.noire.html"},
    {value: 363, text: "Petit Fuligule", link: "../oiseaux/"},
    {value: 364, text: "Fuligule à tête rouge", link: "../oiseaux/fuligule.a.tete.rouge.html"},
    {value: 365, text: "Fulmar boréal", link: "../oiseaux/fulmar.boreal.html"},
    {value: 366, text: "Gallinule africaine", link: "../oiseaux/gallinule.africaine.html"},
    {value: 367, text: "Gallinule d'Amérique", link: "../oiseaux/gallinule.d.amerique.html"},
    {value: 368, text: "Gallinule poule-d'eau", link: "../oiseaux/gallinule.poule-d.eau.html"},
    {value: 369, text: "Ganga cata", link: "../oiseaux/ganga.cata.html"},
    {value: 370, text: "Ganga tacheté", link: "../oiseaux/ganga.tachete.html"},
    {value: 371, text: "Ganga unibande", link: "../oiseaux/ganga.unibande.html"},
    {value: 372, text: "Ganga à ventre brun", link: "../oiseaux/ganga.a.ventre.brun.html"},
    {value: 373, text: "Garde-boeufs d'Asie", link: "../oiseaux/garde-boeufs.d.asie.html"},
    {value: 374, text: "Gardeboeuf d'Asie", link: "../oiseaux/"},
    {value: 375, text: "Garrot albéole", link: "../oiseaux/garrot.albeole.html"},
    {value: 376, text: "Petit Garrot", link: "../oiseaux/garrot.albeole.html"},
    {value: 377, text: "Garrot d'Islande", link: "../oiseaux/garrot.d.islande.html"},
    {value: 378, text: "Garrot à oeil d'or", link: "../oiseaux/garrot.a.oeil.d.or.html"},
    {value: 379, text: "Geai des chênes", link: "../oiseaux/geai.des.chenes.html"},
    {value: 380, text: "Glaréole orientale", link: "../oiseaux/glareole.orientale.html"},
    {value: 381, text: "Glaréole à ailes noires", link: "../oiseaux/glareole.a.ailes.noires.html"},
    {value: 382, text: "Glaréole à collier", link: "../oiseaux/glareole.a.collier.html"},
    {value: 383, text: "Gobemouche brun", link: "../oiseaux/gobemouche.brun.html"},
    {value: 384, text: "Gobemouche de l'Atlas", link: "../oiseaux/gobemouche.de.l.atlas.html"},
    {value: 385, text: "Gobemouche de la taïga", link: "../oiseaux/gobemouche.de.la.taiga.html"},
    {value: 386, text: "Gobemouche de Sibérie", link: "../oiseaux/gobemouche.de.siberie.html"},
    {value: 387, text: "Gobemouche gris", link: "../oiseaux/gobemouche.gris.html"},
    {value: 388, text: "Gobemouche mugimaki", link: "../oiseaux/gobemouche.mugimaki.html"},
    {value: 389, text: "Gobemouche nain", link: "../oiseaux/gobemouche.nain.html"},
    {value: 390, text: "Gobemouche noir", link: "../oiseaux/gobemouche.noir.html"},
    {value: 391, text: "Gobemouche à collier", link: "../oiseaux/gobemouche.a.collier.html"},
    {value: 392, text: "Gobemouche à demi-collier", link: "../oiseaux/gobemouche.a.demi-collier.html"},
    {value: 393, text: "Goglu des prés", link: "../oiseaux/goglu.des.pres.html"},
    {value: 394, text: "Gorgebleue à miroir", link: "../oiseaux/gorgebleue.a.miroir.html"},
    {value: 395, text: "Goéland argenté", link: "../oiseaux/goeland.argente.html"},
    {value: 396, text: "Goéland bourgmestre", link: "../oiseaux/goeland.bourgmestre.html"},
    {value: 397, text: "Goéland brun", link: "../oiseaux/goeland.brun.html"},
    {value: 398, text: "Goéland cendré", link: "../oiseaux/goeland.cendre.html"},
    {value: 399, text: "Goéland d'Amérique", link: "../oiseaux/goeland.d.amerique.html"},
    {value: 400, text: "Goéland hudsonien", link: "../oiseaux/"},
    {value: 401, text: "Goéland d'Arménie", link: "../oiseaux/goeland.d.armenie.html"},
    {value: 402, text: "Goéland d'Audouin", link: "../oiseaux/goeland.d.audouin.html"},
    {value: 403, text: "Goéland de la Véga", link: "../oiseaux/goeland.de.la.vega.html"},
    {value: 404, text: "Goéland dominicain", link: "../oiseaux/goeland.dominicain.html"},
    {value: 405, text: "Goéland ichthyaète", link: "../oiseaux/goeland.ichthyaete.html"},
    {value: 406, text: "Goéland leucophée", link: "../oiseaux/goeland.leucophee.html"},
    {value: 407, text: "Goéland marin", link: "../oiseaux/goeland.marin.html"},
    {value: 408, text: "Goéland pontique", link: "../oiseaux/goeland.pontique.html"},
    {value: 409, text: "Goéland railleur", link: "../oiseaux/goeland.railleur.html"},
    {value: 410, text: "Goéland à ailes blanches", link: "../oiseaux/goeland.a.ailes.blanches.html"},
    {value: 411, text: "Goéland arctique", link: "../oiseaux/goeland.a.ailes.blanches.html"},
    {value: 412, text: "Goéland à ailes grises", link: "../oiseaux/goeland.a.ailes.grises.html"},
    {value: 413, text: "Goéland à bec cerclé", link: "../oiseaux/goeland.a.bec.cercle.html"},
    {value: 414, text: "Goéland à bec court", link: "../oiseaux/goeland.a.bec.court.html"},
    {value: 415, text: "Goéland à iris blanc", link: "../oiseaux/goeland.a.iris.blanc.html"},
    {value: 416, text: "Goéland à manteau ardoisé", link: "../oiseaux/goeland.a.manteau.ardoise.html"},
    {value: 417, text: "Goéland à queue noire", link: "../oiseaux/goeland.a.queue.noire.html"},
    {value: 418, text: "Grand-duc ascalaphe", link: "../oiseaux/grand-duc.ascalaphe.html"},
    {value: 419, text: "Grand-duc d'Europe", link: "../oiseaux/grand-duc.d.europe.html"},
    {value: 420, text: "Grande Aigrette", link: "../oiseaux/grande.aigrette.html"},
    {value: 421, text: "Grand Corbeau", link: "../oiseaux/grand.corbeau.html"},
    {value: 422, text: "Grand Cormoran", link: "../oiseaux/grand.cormoran.html"},
    {value: 423, text: "Grand Gravelot", link: "../oiseaux/grand.gravelot.html"},
    {value: 424, text: "Pluvier grand-gravelot", link: "../oiseaux/grand.gravelot.html"},
    {value: 425, text: "Grand Grèbe", link: "../oiseaux/grand.grebe.html"},
    {value: 426, text: "Grand Héron", link: "../oiseaux/grand.heron.html"},
    {value: 427, text: "Grand Labbe", link: "../oiseaux/grand.labbe.html"},
    {value: 428, text: "Grand Tétras", link: "../oiseaux/grand.tetras.html"},
    {value: 429, text: "Gravelot de Leschenault", link: "../oiseaux/gravelot.de.leschenault.html"},
    {value: 430, text: "Pluvier de Leschenault", link: "../oiseaux/gravelot.de.leschenault.html"},
    {value: 431, text: "Gravelot kildir", link: "../oiseaux/gravelot.kildir.html"},
    {value: 432, text: "Pluvier kildir", link: "../oiseaux/gravelot.kildir.html"},
    {value: 433, text: "Gravelot mongol", link: "../oiseaux/gravelot.mongol.html"},
    {value: 434, text: "Pluvier de Mongolie", link: "../oiseaux/gravelot.mongol.html"},
    {value: 435, text: "Gravelot neigeux", link: "../oiseaux/gravelot.neigeux.html"},
    {value: 436, text: "Pluvier neigeux", link: "../oiseaux/"},
    {value: 437, text: "Gravelot oriental", link: "../oiseaux/gravelot.oriental.html"},
    {value: 438, text: "Pluvier oriental", link: "../oiseaux/gravelot.oriental.html"},
    {value: 439, text: "Gravelot pâtre", link: "../oiseaux/gravelot.patre.html"},
    {value: 440, text: "Pluvier pâtre", link: "../oiseaux/gravelot.patre.html"},
    {value: 441, text: "Gravelot semipalmé", link: "../oiseaux/gravelot.semipalme.html"},
    {value: 442, text: "Pluvier semipalmé", link: "../oiseaux/gravelot.semipalme.html"},
    {value: 443, text: "Gravelot à collier interrompu", link: "../oiseaux/gravelot.a.collier.interrompu.html"},
    {value: 444, text: "Pluvier à collier interrompu", link: "../oiseaux/gravelot.a.collier.interrompu.html"},
    {value: 445, text: "Grimpereau des bois", link: "../oiseaux/grimpereau.des.bois.html"},
    {value: 446, text: "Grimpereau des jardins", link: "../oiseaux/grimpereau.des.jardins.html"},
    {value: 447, text: "Grive dama", link: "../oiseaux/grive.dama.html"},
    {value: 448, text: "Grive des bois", link: "../oiseaux/grive.des.bois.html"},
    {value: 449, text: "Grive de Naumann", link: "../oiseaux/grive.de.naumann.html"},
    {value: 450, text: "Grive de Sibérie", link: "../oiseaux/grive.de.siberie.html"},
    {value: 451, text: "Grive dorée", link: "../oiseaux/grive.doree.html"},
    {value: 452, text: "Grive draine", link: "../oiseaux/grive.draine.html"},
    {value: 453, text: "Grive fauve", link: "../oiseaux/grive.fauve.html"},
    {value: 454, text: "Grive litorne", link: "../oiseaux/grive.litorne.html"},
    {value: 455, text: "Grive mauvis", link: "../oiseaux/grive.mauvis.html"},
    {value: 456, text: "Grive musicienne", link: "../oiseaux/grive.musicienne.html"},
    {value: 457, text: "Grive obscure", link: "../oiseaux/grive.obscure.html"},
    {value: 458, text: "Merle obscur", link: "../oiseaux/grive.obscure.html"},
    {value: 459, text: "Grive solitaire", link: "../oiseaux/grive.solitaire.html"},
    {value: 460, text: "Grive à ailes rousses", link: "../oiseaux/grive.a.ailes.rousses.html"},
    {value: 461, text: "Grive à collier", link: "../oiseaux/grive.a.collier.html"},
    {value: 462, text: "Grive à dos olive", link: "../oiseaux/grive.a.dos.olive.html"},
    {value: 463, text: "Grive à gorge noire", link: "../oiseaux/grive.a.gorge.noire.html"},
    {value: 464, text: "Grive à gorge rousse", link: "../oiseaux/grive.a.gorge.rousse.html"},
    {value: 465, text: "Grive à joues grises", link: "../oiseaux/grive.a.joues.grises.html"},
    {value: 466, text: "Grosbec casse-noyaux", link: "../oiseaux/grosbec.casse-noyaux.html"},
    {value: 467, text: "Gros-bec casse-noyaux", link: "../oiseaux/grosbec.casse-noyaux.html"},
    {value: 468, text: "Grosbec errant", link: "../oiseaux/grosbec.errant.html"},
    {value: 469, text: "Gros-bec errant", link: "../oiseaux/"},
    {value: 470, text: "Grue cendrée", link: "../oiseaux/grue.cendree.html"},
    {value: 471, text: "Grue demoiselle", link: "../oiseaux/grue.demoiselle.html"},
    {value: 472, text: "Grue de Sibérie", link: "../oiseaux/grue.de.siberie.html"},
    {value: 473, text: "Grue du Canada", link: "../oiseaux/grue.du.canada.html"},
    {value: 474, text: "Grue moine", link: "../oiseaux/grue.moine.html"},
    {value: 475, text: "Grèbe castagneux", link: "../oiseaux/grebe.castagneux.html"},
    {value: 476, text: "Grèbe esclavon", link: "../oiseaux/grebe.esclavon.html"},
    {value: 477, text: "Grèbe huppé", link: "../oiseaux/grebe.huppe.html"},
    {value: 478, text: "Grèbe jougris", link: "../oiseaux/grebe.jougris.html"},
    {value: 479, text: "Grèbe à bec bigarré", link: "../oiseaux/grebe.a.bec.bigarre.html"},
    {value: 480, text: "Grèbe à cou noir", link: "../oiseaux/grebe.a.cou.noir.html"},
    {value: 481, text: "Guifette leucoptère", link: "../oiseaux/guifette.leucoptere.html"},
    {value: 482, text: "Guifette moustac", link: "../oiseaux/guifette.moustac.html"},
    {value: 483, text: "Guifette noire", link: "../oiseaux/guifette.noire.html"},
    {value: 484, text: "Guillemot colombin", link: "../oiseaux/guillemot.colombin.html"},
    {value: 485, text: "Guillemot de Brünnich", link: "../oiseaux/guillemot.de.brunnich.html"},
    {value: 486, text: "Guillemot de Troïl", link: "../oiseaux/guillemot.de.troil.html"},
    {value: 487, text: "Guillemot marmette", link: "../oiseaux/guillemot.de.troil.html"},
    {value: 488, text: "Guillemot à cou blanc", link: "../oiseaux/guillemot.a.cou.blanc.html"},
    {value: 489, text: "Guillemot à long bec", link: "../oiseaux/guillemot.a.long.bec.html"},
    {value: 490, text: "Guillemot à miroir", link: "../oiseaux/guillemot.a.miroir.html"},
    {value: 491, text: "Guiraca bleu", link: "../oiseaux/guiraca.bleu.html"},
    {value: 492, text: "Guêpier d'Europe", link: "../oiseaux/guepier.d.europe.html"},
    {value: 493, text: "Guêpier d'Orient", link: "../oiseaux/guepier.d.orient.html"},
    {value: 494, text: "Guêpier de Perse", link: "../oiseaux/guepier.de.perse.html"},
    {value: 495, text: "Guêpier à sourcils bleus", link: "../oiseaux/guepier.a.sourcils.bleus.html"},
    {value: 496, text: "Gypaète barbu", link: "../oiseaux/gypaete.barbu.html"},
    {value: 497, text: "Gélinotte des bois", link: "../oiseaux/gelinotte.des.bois.html"},
    {value: 498, text: "Harelde boréale", link: "../oiseaux/harelde.boreale.html"},
    {value: 499, text: "Harelde kakawi", link: "../oiseaux/harelde.boreale.html"},
    {value: 500, text: "Harfang des neiges", link: "../oiseaux/harfang.des.neiges.html"},
    {value: 501, text: "Harle bièvre", link: "../oiseaux/harle.bievre.html"},
    {value: 502, text: "Grand Harle", link: "../oiseaux/harle.bievre.html"},
    {value: 503, text: "Harle couronné", link: "../oiseaux/harle.couronne.html"},
    {value: 504, text: "Harle huppé", link: "../oiseaux/harle.huppe.html"},
    {value: 505, text: "Harle piette", link: "../oiseaux/harle.piette.html"},
    {value: 506, text: "Hibou des marais", link: "../oiseaux/hibou.des.marais.html"},
    {value: 507, text: "Hibou du Cap", link: "../oiseaux/hibou.du.cap.html"},
    {value: 508, text: "Hibou moyen-duc", link: "../oiseaux/hibou.moyen-duc.html"},
    {value: 509, text: "Hirondelle bicolore", link: "../oiseaux/hirondelle.bicolore.html"},
    {value: 510, text: "Hirondelle de Bonaparte", link: "../oiseaux/hirondelle.de.bonaparte.html"},
    {value: 511, text: "Hirondelle de fenêtre", link: "../oiseaux/hirondelle.de.fenetre.html"},
    {value: 512, text: "Hirondelle de Pallas", link: "../oiseaux/hirondelle.de.pallas.html"},
    {value: 513, text: "Hirondelle de rivage", link: "../oiseaux/hirondelle.de.rivage.html"},
    {value: 514, text: "Hirondelle de rochers", link: "../oiseaux/hirondelle.de.rochers.html"},
    {value: 515, text: "Hirondelle du désert", link: "../oiseaux/hirondelle.du.desert.html"},
    {value: 516, text: "Hirondelle isabelline", link: "../oiseaux/hirondelle.isabelline.html"},
    {value: 517, text: "Hirondelle noire", link: "../oiseaux/hirondelle.noire.html"},
    {value: 518, text: "Hirondelle paludicole", link: "../oiseaux/hirondelle.paludicole.html"},
    {value: 519, text: "Hirondelle pâle", link: "../oiseaux/hirondelle.pale.html"},
    {value: 520, text: "Hirondelle rousseline", link: "../oiseaux/hirondelle.rousseline.html"},
    {value: 521, text: "Hirondelle rustique", link: "../oiseaux/hirondelle.rustique.html"},
    {value: 522, text: "Hirondelle à ailes hérissées", link: "../oiseaux/hirondelle.a.ailes.herissees.html"},
    {value: 523, text: "Hirondelle à front blanc", link: "../oiseaux/hirondelle.a.front.blanc.html"},
    {value: 524, text: "Huppe d'Afrique", link: "../oiseaux/huppe.d.afrique.html"},
    {value: 525, text: "Huppe fasciée", link: "../oiseaux/huppe.fasciee.html"},
    {value: 526, text: "Huîtrier d'Amérique", link: "../oiseaux/huitrier.d.amerique.html"},
    {value: 527, text: "Huîtrier pie", link: "../oiseaux/huitrier.pie.html"},
    {value: 528, text: "Hypolaïs bottée", link: "../oiseaux/hypolais.bottee.html"},
    {value: 529, text: "Hypolaïs d'Upcher", link: "../oiseaux/hypolais.d.upcher.html"},
    {value: 530, text: "Hypolaïs des oliviers", link: "../oiseaux/hypolais.des.oliviers.html"},
    {value: 531, text: "Hypolaïs ictérine", link: "../oiseaux/hypolais.icterine.html"},
    {value: 532, text: "Hypolaïs obscure", link: "../oiseaux/hypolais.obscure.html"},
    {value: 533, text: "Hypolaïs polyglotte", link: "../oiseaux/hypolais.polyglotte.html"},
    {value: 534, text: "Hypolaïs pâle", link: "../oiseaux/hypolais.pale.html"},
    {value: 535, text: "Hypolaïs rama", link: "../oiseaux/hypolais.rama.html"},
    {value: 536, text: "Héron cendré", link: "../oiseaux/heron.cendre.html"},
    {value: 537, text: "Héron garde-boeufs", link: "../oiseaux/heron.garde-boeufs.html"},
    {value: 538, text: "Héron intermédiaire", link: "../oiseaux/heron.intermediaire.html"},
    {value: 539, text: "Héron mélanocéphale", link: "../oiseaux/heron.melanocephale.html"},
    {value: 540, text: "Héron pourpré", link: "../oiseaux/heron.pourpre.html"},
    {value: 541, text: "Héron strié", link: "../oiseaux/heron.strie.html"},
    {value: 542, text: "Héron vert", link: "../oiseaux/heron.vert.html"},
    {value: 543, text: "Ibis chauve", link: "../oiseaux/ibis.chauve.html"},
    {value: 544, text: "Ibis falcinelle", link: "../oiseaux/ibis.falcinelle.html"},
    {value: 545, text: "Ibis sacré", link: "../oiseaux/ibis.sacre.html"},
    {value: 546, text: "Inséparable de Fischer", link: "../oiseaux/inseparable.de.fischer.html"},
    {value: 547, text: "Iranie à gorge blanche", link: "../oiseaux/iranie.a.gorge.blanche.html"},
    {value: 548, text: "Jaseur boréal", link: "../oiseaux/jaseur.boreal.html"},
    {value: 549, text: "Jaseur d'Amérique", link: "../oiseaux/jaseur.d.amerique.html"},
    {value: 550, text: "Junco ardoisé", link: "../oiseaux/junco.ardoise.html"},
    {value: 551, text: "Labbe de McCormick", link: "../oiseaux/labbe.de.mccormick.html"},
    {value: 552, text: "Labbe parasite", link: "../oiseaux/labbe.parasite.html"},
    {value: 553, text: "Labbe pomarin", link: "../oiseaux/labbe.pomarin.html"},
    {value: 554, text: "Labbe à longue queue", link: "../oiseaux/labbe.a.longue.queue.html"},
    {value: 555, text: "Lagopède alpin", link: "../oiseaux/lagopede.alpin.html"},
    {value: 556, text: "Lagopède des saules", link: "../oiseaux/lagopede.des.saules.html"},
    {value: 557, text: "Linotte mélodieuse", link: "../oiseaux/linotte.melodieuse.html"},
    {value: 558, text: "Linotte à bec jaune", link: "../oiseaux/linotte.a.bec.jaune.html"},
    {value: 559, text: "Locustelle de Pallas", link: "../oiseaux/locustelle.de.pallas.html"},
    {value: 560, text: "Locustelle fasciée", link: "../oiseaux/locustelle.fasciee.html"},
    {value: 561, text: "Locustelle fluviatile", link: "../oiseaux/locustelle.fluviatile.html"},
    {value: 562, text: "Locustelle lancéolée", link: "../oiseaux/locustelle.lanceolee.html"},
    {value: 563, text: "Locustelle luscinioïde", link: "../oiseaux/locustelle.luscinioide.html"},
    {value: 564, text: "Locustelle tachetée", link: "../oiseaux/locustelle.tachetee.html"},
    {value: 565, text: "Loriot d'Europe", link: "../oiseaux/loriot.d.europe.html"},
    {value: 566, text: "Lusciniole à moustaches", link: "../oiseaux/lusciniole.a.moustaches.html"},
    {value: 567, text: "Léiothrix jaune", link: "../oiseaux/leiothrix.jaune.html"},
    {value: 568, text: "Macareux cornu", link: "../oiseaux/macareux.cornu.html"},
    {value: 569, text: "Macareux huppé", link: "../oiseaux/macareux.huppe.html"},
    {value: 570, text: "Macareux moine", link: "../oiseaux/macareux.moine.html"},
    {value: 571, text: "Macreuse brune", link: "../oiseaux/macreuse.brune.html"},
    {value: 572, text: "Macreuse de Sibérie", link: "../oiseaux/macreuse.de.siberie.html"},
    {value: 573, text: "Macreuse noire", link: "../oiseaux/macreuse.noire.html"},
    {value: 574, text: "Macreuse à ailes blanches", link: "../oiseaux/macreuse.a.ailes.blanches.html"},
    {value: 575, text: "Macreuse à bec jaune", link: "../oiseaux/macreuse.a.bec.jaune.html"},
    {value: 576, text: "Macreuse à front blanc", link: "../oiseaux/macreuse.a.front.blanc.html"},
    {value: 577, text: "Mandarin d'Australie", link: "../oiseaux/mandarin.d.australie.html"},
    {value: 578, text: "Marabout d'Afrique", link: "../oiseaux/marabout.d.afrique.html"},
    {value: 579, text: "Marouette de Baillon", link: "../oiseaux/marouette.de.baillon.html"},
    {value: 580, text: "Marouette de Caroline", link: "../oiseaux/marouette.de.caroline.html"},
    {value: 581, text: "Marouette ponctuée", link: "../oiseaux/marouette.ponctuee.html"},
    {value: 582, text: "Marouette poussin", link: "../oiseaux/marouette.poussin.html"},
    {value: 583, text: "Marouette rayée", link: "../oiseaux/marouette.rayee.html"},
    {value: 584, text: "Râle rayé", link: "../oiseaux/"},
    {value: 585, text: "Martin-chasseur de Smyrne", link: "../oiseaux/martin-chasseur.de.smyrne.html"},
    {value: 586, text: "Martin-pêcheur d'Amérique", link: "../oiseaux/martin-pecheur.d.amerique.html"},
    {value: 587, text: "Martin-pêcheur d'Europe", link: "../oiseaux/martin-pecheur.d.europe.html"},
    {value: 588, text: "Martin-pêcheur pie", link: "../oiseaux/martin-pecheur.pie.html"},
    {value: 589, text: "Alcyon pie", link: "../oiseaux/martin-pecheur.pie.html"},
    {value: 590, text: "Martinet cafre", link: "../oiseaux/martinet.cafre.html"},
    {value: 591, text: "Martinet des maisons", link: "../oiseaux/martinet.des.maisons.html"},
    {value: 592, text: "Martinet de Sibérie", link: "../oiseaux/martinet.de.siberie.html"},
    {value: 593, text: "Martinet noir", link: "../oiseaux/martinet.noir.html"},
    {value: 594, text: "Martinet pâle", link: "../oiseaux/martinet.pale.html"},
    {value: 595, text: "Martinet ramoneur", link: "../oiseaux/martinet.ramoneur.html"},
    {value: 596, text: "Martinet unicolore", link: "../oiseaux/martinet.unicolore.html"},
    {value: 597, text: "Martinet à ventre blanc", link: "../oiseaux/martinet.a.ventre.blanc.html"},
    {value: 598, text: "Martinet épineux", link: "../oiseaux/martinet.epineux.html"},
    {value: 599, text: "Martin huppé", link: "../oiseaux/martin.huppe.html"},
    {value: 600, text: "Martin triste", link: "../oiseaux/martin.triste.html"},
    {value: 601, text: "Mergule nain", link: "../oiseaux/mergule.nain.html"},
    {value: 602, text: "Merle d'Amérique", link: "../oiseaux/merle.d.amerique.html"},
    {value: 603, text: "Merle noir", link: "../oiseaux/merle.noir.html"},
    {value: 604, text: "Merle pâle", link: "../oiseaux/merle.pale.html"},
    {value: 605, text: "Merle unicolore", link: "../oiseaux/merle.unicolore.html"},
    {value: 606, text: "Merle à plastron", link: "../oiseaux/merle.a.plastron.html"},
    {value: 607, text: "Milan noir", link: "../oiseaux/milan.noir.html"},
    {value: 608, text: "Milan royal", link: "../oiseaux/milan.royal.html"},
    {value: 609, text: "Milan à bec jaune", link: "../oiseaux/milan.a.bec.jaune.html"},
    {value: 610, text: "Milan d'Afrique", link: "../oiseaux/"},
    {value: 611, text: "Milan à queue fourchue", link: "../oiseaux/milan.a.queue.fourchue.html"},
    {value: 612, text: "Naucler à queue fourchue", link: "../oiseaux/milan.a.queue.fourchue.html"},
    {value: 613, text: "Moineau blanc", link: "../oiseaux/moineau.blanc.html"},
    {value: 614, text: "Moineau cisalpin", link: "../oiseaux/moineau.cisalpin.html"},
    {value: 615, text: "Moineau de la mer Morte", link: "../oiseaux/moineau.de.la.mer.morte.html"},
    {value: 616, text: "Moineau domestique", link: "../oiseaux/moineau.domestique.html"},
    {value: 617, text: "Moineau espagnol", link: "../oiseaux/moineau.espagnol.html"},
    {value: 618, text: "Moineau friquet", link: "../oiseaux/moineau.friquet.html"},
    {value: 619, text: "Moineau pâle", link: "../oiseaux/moineau.pale.html"},
    {value: 620, text: "Moineau soulcie", link: "../oiseaux/moineau.soulcie.html"},
    {value: 621, text: "Monticole bleu", link: "../oiseaux/monticole.bleu.html"},
    {value: 622, text: "Monticole de roche", link: "../oiseaux/monticole.de.roche.html"},
    {value: 623, text: "Moqueur chat", link: "../oiseaux/moqueur.chat.html"},
    {value: 624, text: "Moqueur polyglotte", link: "../oiseaux/moqueur.polyglotte.html"},
    {value: 625, text: "Moqueur roux", link: "../oiseaux/moqueur.roux.html"},
    {value: 626, text: "Moucherolle des aulnes", link: "../oiseaux/moucherolle.des.aulnes.html"},
    {value: 627, text: "Moucherolle des saules", link: "../oiseaux/moucherolle.des.saules.html"},
    {value: 628, text: "Moucherolle phébi", link: "../oiseaux/moucherolle.phebi.html"},
    {value: 629, text: "Moucherolle tchébec", link: "../oiseaux/moucherolle.tchebec.html"},
    {value: 630, text: "Moucherolle vert", link: "../oiseaux/moucherolle.vert.html"},
    {value: 631, text: "Moucherolle à côtés olive", link: "../oiseaux/moucherolle.a.cotes.olive.html"},
    {value: 632, text: "Moucherolle à ventre jaune", link: "../oiseaux/moucherolle.a.ventre.jaune.html"},
    {value: 633, text: "Mouette atricille", link: "../oiseaux/mouette.atricille.html"},
    {value: 634, text: "Mouette blanche", link: "../oiseaux/mouette.blanche.html"},
    {value: 635, text: "Mouette de Bonaparte", link: "../oiseaux/mouette.de.bonaparte.html"},
    {value: 636, text: "Mouette de Franklin", link: "../oiseaux/mouette.de.franklin.html"},
    {value: 637, text: "Mouette de Ross", link: "../oiseaux/mouette.de.ross.html"},
    {value: 638, text: "Mouette rosée", link: "../oiseaux/mouette.de.ross.html"},
    {value: 639, text: "Mouette de Sabine", link: "../oiseaux/mouette.de.sabine.html"},
    {value: 640, text: "Mouette mélanocéphale", link: "../oiseaux/mouette.melanocephale.html"},
    {value: 641, text: "Mouette pygmée", link: "../oiseaux/mouette.pygmee.html"},
    {value: 642, text: "Mouette relique", link: "../oiseaux/mouette.relique.html"},
    {value: 643, text: "Mouette rieuse", link: "../oiseaux/mouette.rieuse.html"},
    {value: 644, text: "Mouette tridactyle", link: "../oiseaux/mouette.tridactyle.html"},
    {value: 645, text: "Mouette à tête grise", link: "../oiseaux/mouette.a.tete.grise.html"},
    {value: 646, text: "Mésangeai imitateur", link: "../oiseaux/mesangeai.imitateur.html"},
    {value: 647, text: "Mésange azurée", link: "../oiseaux/mesange.azuree.html"},
    {value: 648, text: "Mésange bleue", link: "../oiseaux/mesange.bleue.html"},
    {value: 649, text: "Mésange boréale", link: "../oiseaux/mesange.boreale.html"},
    {value: 650, text: "Mésange charbonnière", link: "../oiseaux/mesange.charbonniere.html"},
    {value: 651, text: "Mésange huppée", link: "../oiseaux/mesange.huppee.html"},
    {value: 652, text: "Mésange lapone", link: "../oiseaux/mesange.lapone.html"},
    {value: 653, text: "Mésange lugubre", link: "../oiseaux/mesange.lugubre.html"},
    {value: 654, text: "Mésange noire", link: "../oiseaux/mesange.noire.html"},
    {value: 655, text: "Mésange nonnette", link: "../oiseaux/mesange.nonnette.html"},
    {value: 656, text: "Mésange nord-africaine", link: "../oiseaux/mesange.nord-africaine.html"},
    {value: 657, text: "Nette rousse", link: "../oiseaux/nette.rousse.html"},
    {value: 658, text: "Ninoxe hirsute", link: "../oiseaux/ninoxe.hirsute.html"},
    {value: 659, text: "Niverolle alpine", link: "../oiseaux/niverolle.alpine.html"},
    {value: 660, text: "Noddi brun", link: "../oiseaux/noddi.brun.html"},
    {value: 661, text: "Nymphée fuligineuse", link: "../oiseaux/nymphee.fuligineuse.html"},
    {value: 662, text: "Rougequeue fuligineux", link: "../oiseaux/nymphee.fuligineuse.html"},
    {value: 663, text: "Océanite culblanc", link: "../oiseaux/oceanite.culblanc.html"},
    {value: 664, text: "Océanite cul-blanc", link: "../oiseaux/oceanite.culblanc.html"},
    {value: 665, text: "Océanite de Castro", link: "../oiseaux/oceanite.de.castro.html"},
    {value: 666, text: "Océanite de Monteiro", link: "../oiseaux/oceanite.de.monteiro.html"},
    {value: 667, text: "Océanite de Swinhoe", link: "../oiseaux/oceanite.de.swinhoe.html"},
    {value: 668, text: "Océanite de Wilson", link: "../oiseaux/oceanite.de.wilson.html"},
    {value: 669, text: "Océanite frégate", link: "../oiseaux/oceanite.fregate.html"},
    {value: 670, text: "Océanite tempête", link: "../oiseaux/oceanite.tempete.html"},
    {value: 671, text: "Océanite à ventre noir", link: "../oiseaux/oceanite.a.ventre.noir.html"},
    {value: 672, text: "Oedicnème criard", link: "../oiseaux/oedicneme.criard.html"},
    {value: 673, text: "Oie cendrée", link: "../oiseaux/oie.cendree.html"},
    {value: 674, text: "Oie des moissons", link: "../oiseaux/oie.des.moissons.html"},
    {value: 675, text: "Oie des neiges", link: "../oiseaux/oie.des.neiges.html"},
    {value: 676, text: "Oie de la toundra", link: "../oiseaux/oie.de.la.toundra.html"},
    {value: 677, text: "Oie de Ross", link: "../oiseaux/oie.de.ross.html"},
    {value: 678, text: "Oie empereur", link: "../oiseaux/oie.empereur.html"},
    {value: 679, text: "Oie naine", link: "../oiseaux/oie.naine.html"},
    {value: 680, text: "Oie rieuse", link: "../oiseaux/oie.rieuse.html"},
    {value: 681, text: "Oie à bec court", link: "../oiseaux/oie.a.bec.court.html"},
    {value: 682, text: "Oie à tête barrée", link: "../oiseaux/oie.a.tete.barree.html"},
    {value: 683, text: "Oriole du Nord", link: "../oiseaux/oriole.du.nord.html"},
    {value: 684, text: "Oriole de Baltimore", link: "../oiseaux/oriole.du.nord.html"},
    {value: 685, text: "Orite à longue queue", link: "../oiseaux/orite.a.longue.queue.html"},
    {value: 686, text: "Mésange à longue queue", link: "../oiseaux/orite.a.longue.queue.html"},
    {value: 687, text: "Ouette d'Égypte", link: "../oiseaux/ouette.d.egypte.html"},
    {value: 688, text: "Outarde barbue", link: "../oiseaux/outarde.barbue.html"},
    {value: 689, text: "Grande Outarde", link: "../oiseaux/outarde.barbue.html"},
    {value: 690, text: "Outarde canepetière", link: "../oiseaux/outarde.canepetiere.html"},
    {value: 691, text: "Outarde de Macqueen", link: "../oiseaux/outarde.de.macqueen.html"},
    {value: 692, text: "Outarde houbara", link: "../oiseaux/outarde.houbara.html"},
    {value: 693, text: "Panure à moustaches", link: "../oiseaux/panure.a.moustaches.html"},
    {value: 694, text: "Paon bleu", link: "../oiseaux/paon.bleu.html"},
    {value: 695, text: "Paradoxornis de Webb", link: "../oiseaux/paradoxornis.de.webb.html"},
    {value: 696, text: "Paradoxornis à gorge cendrée", link: "../oiseaux/paradoxornis.a.gorge.cendree.html"},
    {value: 697, text: "Paruline azurée", link: "../oiseaux/paruline.azuree.html"},
    {value: 698, text: "Paruline bleue", link: "../oiseaux/paruline.bleue.html"},
    {value: 699, text: "Paruline couronnée", link: "../oiseaux/paruline.couronnee.html"},
    {value: 700, text: "Paruline d'Audubon", link: "../oiseaux/paruline.d.audubon.html"},
    {value: 701, text: "Paruline des pins", link: "../oiseaux/paruline.des.pins.html"},
    {value: 702, text: "Paruline des prés", link: "../oiseaux/paruline.des.pres.html"},
    {value: 703, text: "Paruline des ruisseaux", link: "../oiseaux/paruline.des.ruisseaux.html"},
    {value: 704, text: "Paruline du Canada", link: "../oiseaux/paruline.du.canada.html"},
    {value: 705, text: "Paruline flamboyante", link: "../oiseaux/paruline.flamboyante.html"},
    {value: 706, text: "Paruline hochequeue", link: "../oiseaux/paruline.hochequeue.html"},
    {value: 707, text: "Paruline jaune", link: "../oiseaux/paruline.jaune.html"},
    {value: 708, text: "Paruline des mangroves", link: "../oiseaux/"},
    {value: 709, text: "Paruline masquée", link: "../oiseaux/paruline.masquee.html"},
    {value: 710, text: "Paruline noir et blanc", link: "../oiseaux/paruline.noir.et.blanc.html"},
    {value: 711, text: "Paruline obscure", link: "../oiseaux/paruline.obscure.html"},
    {value: 712, text: "Paruline orangée", link: "../oiseaux/paruline.orangee.html"},
    {value: 713, text: "Paruline polyglotte", link: "../oiseaux/paruline.polyglotte.html"},
    {value: 714, text: "Ictérie polyglotte", link: "../oiseaux/"},
    {value: 715, text: "Paruline rayée", link: "../oiseaux/paruline.rayee.html"},
    {value: 716, text: "Paruline tigrée", link: "../oiseaux/paruline.tigree.html"},
    {value: 717, text: "Paruline triste", link: "../oiseaux/paruline.triste.html"},
    {value: 718, text: "Paruline verdâtre", link: "../oiseaux/paruline.verdatre.html"},
    {value: 719, text: "Paruline à ailes bleues", link: "../oiseaux/paruline.a.ailes.bleues.html"},
    {value: 720, text: "Paruline à ailes dorées", link: "../oiseaux/paruline.a.ailes.dorees.html"},
    {value: 721, text: "Paruline à calotte noire", link: "../oiseaux/paruline.a.calotte.noire.html"},
    {value: 722, text: "Paruline à capuchon", link: "../oiseaux/paruline.a.capuchon.html"},
    {value: 723, text: "Paruline à collier", link: "../oiseaux/paruline.a.collier.html"},
    {value: 724, text: "Paruline à couronne rousse", link: "../oiseaux/paruline.a.couronne.rousse.html"},
    {value: 725, text: "Paruline à croupion jaune", link: "../oiseaux/paruline.a.croupion.jaune.html"},
    {value: 726, text: "Paruline à flancs marron", link: "../oiseaux/paruline.a.flancs.marron.html"},
    {value: 727, text: "Paruline à gorge grise", link: "../oiseaux/paruline.a.gorge.grise.html"},
    {value: 728, text: "Paruline à gorge jaune", link: "../oiseaux/paruline.a.gorge.jaune.html"},
    {value: 729, text: "Paruline à gorge noire", link: "../oiseaux/paruline.a.gorge.noire.html"},
    {value: 730, text: "Paruline à gorge orangée", link: "../oiseaux/paruline.a.gorge.orangee.html"},
    {value: 731, text: "Paruline à joues grises", link: "../oiseaux/paruline.a.joues.grises.html"},
    {value: 732, text: "Paruline à poitrine baie", link: "../oiseaux/paruline.a.poitrine.baie.html"},
    {value: 733, text: "Paruline à tête cendrée", link: "../oiseaux/paruline.a.tete.cendree.html"},
    {value: 734, text: "Passerin azuré", link: "../oiseaux/passerin.azure.html"},
    {value: 735, text: "Passerin indigo", link: "../oiseaux/passerin.indigo.html"},
    {value: 736, text: "Percnoptère d'Égypte", link: "../oiseaux/percnoptere.d.egypte.html"},
    {value: 737, text: "Vautour percnoptère", link: "../oiseaux/percnoptere.d.egypte.html"},
    {value: 738, text: "Perdrix bartavelle", link: "../oiseaux/perdrix.bartavelle.html"},
    {value: 739, text: "Perdrix choukar", link: "../oiseaux/perdrix.choukar.html"},
    {value: 740, text: "Perdrix de Daourie", link: "../oiseaux/perdrix.de.daourie.html"},
    {value: 741, text: "Perdrix gambra", link: "../oiseaux/perdrix.gambra.html"},
    {value: 742, text: "Perdrix grise", link: "../oiseaux/perdrix.grise.html"},
    {value: 743, text: "Perdrix rouge", link: "../oiseaux/perdrix.rouge.html"},
    {value: 744, text: "Perriche veuve", link: "../oiseaux/perriche.veuve.html"},
    {value: 745, text: "Conure veuve", link: "../oiseaux/perriche.veuve.html"},
    {value: 746, text: "Perruche alexandre", link: "../oiseaux/perruche.alexandre.html"},
    {value: 747, text: "Perruche à collier", link: "../oiseaux/perruche.a.collier.html"},
    {value: 748, text: "Petit-duc scops", link: "../oiseaux/petit-duc.scops.html"},
    {value: 749, text: "Petite Sterne", link: "../oiseaux/petite.sterne.html"},
    {value: 750, text: "Petit Blongios", link: "../oiseaux/petit.blongios.html"},
    {value: 751, text: "Petit Gravelot", link: "../oiseaux/petit.gravelot.html"},
    {value: 752, text: "Pluvier petit-gravelot", link: "../oiseaux/petit.gravelot.html"},
    {value: 753, text: "Petit Puffin du Cap-Vert", link: "../oiseaux/petit.puffin.du.cap-vert.html"},
    {value: 754, text: "Puffin de Boyd", link: "../oiseaux/"},
    {value: 755, text: "Phalarope de Wilson", link: "../oiseaux/phalarope.de.wilson.html"},
    {value: 756, text: "Phalarope à bec large", link: "../oiseaux/phalarope.a.bec.large.html"},
    {value: 757, text: "Phalarope à bec étroit", link: "../oiseaux/phalarope.a.bec.etroit.html"},
    {value: 758, text: "Phaéton à bec jaune", link: "../oiseaux/phaeton.a.bec.jaune.html"},
    {value: 759, text: "Phaéton à bec rouge", link: "../oiseaux/phaeton.a.bec.rouge.html"},
    {value: 760, text: "Phragmite aquatique", link: "../oiseaux/phragmite.aquatique.html"},
    {value: 761, text: "Phragmite des joncs", link: "../oiseaux/phragmite.des.joncs.html"},
    {value: 762, text: "Pic cendré", link: "../oiseaux/pic.cendre.html"},
    {value: 763, text: "Pic de Levaillant", link: "../oiseaux/pic.de.levaillant.html"},
    {value: 764, text: "Pic de Sharpe", link: "../oiseaux/pic.de.sharpe.html"},
    {value: 765, text: "Pic flamboyant", link: "../oiseaux/pic.flamboyant.html"},
    {value: 766, text: "Pic maculé", link: "../oiseaux/pic.macule.html"},
    {value: 767, text: "Pic mar", link: "../oiseaux/pic.mar.html"},
    {value: 768, text: "Pic noir", link: "../oiseaux/pic.noir.html"},
    {value: 769, text: "Pic syriaque", link: "../oiseaux/pic.syriaque.html"},
    {value: 770, text: "Pic tridactyle", link: "../oiseaux/pic.tridactyle.html"},
    {value: 771, text: "Pic vert", link: "../oiseaux/pic.vert.html"},
    {value: 772, text: "Pic à dos blanc", link: "../oiseaux/pic.a.dos.blanc.html"},
    {value: 773, text: "Pic épeiche", link: "../oiseaux/pic.epeiche.html"},
    {value: 774, text: "Pic épeichette", link: "../oiseaux/pic.epeichette.html"},
    {value: 775, text: "Pie-grièche boréale", link: "../oiseaux/pie-grieche.boreale.html"},
    {value: 776, text: "Pie-grièche brune", link: "../oiseaux/pie-grieche.brune.html"},
    {value: 777, text: "Pie-grièche du Turkestan", link: "../oiseaux/pie-grieche.du.turkestan.html"},
    {value: 778, text: "Pie-grièche grise", link: "../oiseaux/pie-grieche.grise.html"},
    {value: 779, text: "Pie-grièche isabelle", link: "../oiseaux/pie-grieche.isabelle.html"},
    {value: 780, text: "Pie-grièche masquée", link: "../oiseaux/pie-grieche.masquee.html"},
    {value: 781, text: "Pie-grièche méridionale", link: "../oiseaux/pie-grieche.meridionale.html"},
    {value: 782, text: "Pie-grièche schach", link: "../oiseaux/pie-grieche.schach.html"},
    {value: 783, text: "Pie-grièche à poitrine rose", link: "../oiseaux/pie-grieche.a.poitrine.rose.html"},
    {value: 784, text: "Pie-grièche à tête rousse", link: "../oiseaux/pie-grieche.a.tete.rousse.html"},
    {value: 785, text: "Pie-grièche écorcheur", link: "../oiseaux/pie-grieche.ecorcheur.html"},
    {value: 786, text: "Pie bavarde", link: "../oiseaux/pie.bavarde.html"},
    {value: 787, text: "Pie du Maghreb", link: "../oiseaux/pie.du.maghreb.html"},
    {value: 788, text: "Pie ibérique", link: "../oiseaux/pie.iberique.html"},
    {value: 789, text: "Pie-bleue ibérique", link: "../oiseaux/pie.iberique.html"},
    {value: 790, text: "Pigeon biset", link: "../oiseaux/pigeon.biset.html"},
    {value: 791, text: "Pigeon colombin", link: "../oiseaux/pigeon.colombin.html"},
    {value: 792, text: "Pigeon des lauriers", link: "../oiseaux/pigeon.des.lauriers.html"},
    {value: 793, text: "Pigeon de Bolle", link: "../oiseaux/pigeon.de.bolle.html"},
    {value: 794, text: "Pigeon ramier", link: "../oiseaux/pigeon.ramier.html"},
    {value: 795, text: "Pigeon trocaz", link: "../oiseaux/pigeon.trocaz.html"},
    {value: 796, text: "Pingouin torda", link: "../oiseaux/pingouin.torda.html"},
    {value: 797, text: "Petit Pingouin", link: "../oiseaux/pingouin.torda.html"},
    {value: 798, text: "Pinson bleu", link: "../oiseaux/pinson.bleu.html"},
    {value: 799, text: "Pinson bleu de Grande Canarie", link: "../oiseaux/pinson.bleu.de.grande.canarie.html"},
    {value: 800, text: "Pinson de Grande Canarie", link: "../oiseaux/"},
    {value: 801, text: "Pinson des arbres", link: "../oiseaux/pinson.des.arbres.html"},
    {value: 802, text: "Pinson du Nord", link: "../oiseaux/pinson.du.nord.html"},
    {value: 803, text: "Pintade de Numidie", link: "../oiseaux/pintade.de.numidie.html"},
    {value: 804, text: "Pioui de l'Est", link: "../oiseaux/pioui.de.l.est.html"},
    {value: 805, text: "Pipit des arbres", link: "../oiseaux/pipit.des.arbres.html"},
    {value: 806, text: "Pipit de Berthelot", link: "../oiseaux/pipit.de.berthelot.html"},
    {value: 807, text: "Pipit de Godlewski", link: "../oiseaux/pipit.de.godlewski.html"},
    {value: 808, text: "Pipit de la Petchora", link: "../oiseaux/pipit.de.la.petchora.html"},
    {value: 809, text: "Pipit de Richard", link: "../oiseaux/pipit.de.richard.html"},
    {value: 810, text: "Pipit farlousane", link: "../oiseaux/pipit.farlousane.html"},
    {value: 811, text: "Pipit d'Amérique", link: "../oiseaux/"},
    {value: 812, text: "Pipit farlouse", link: "../oiseaux/pipit.farlouse.html"},
    {value: 813, text: "Pipit maritime", link: "../oiseaux/pipit.maritime.html"},
    {value: 814, text: "Pipit rousseline", link: "../oiseaux/pipit.rousseline.html"},
    {value: 815, text: "Pipit rousset", link: "../oiseaux/pipit.rousset.html"},
    {value: 816, text: "Pipit spioncelle", link: "../oiseaux/pipit.spioncelle.html"},
    {value: 817, text: "Pipit à dos olive", link: "../oiseaux/pipit.a.dos.olive.html"},
    {value: 818, text: "Pipit à gorge rousse", link: "../oiseaux/pipit.a.gorge.rousse.html"},
    {value: 819, text: "Pipit à long bec", link: "../oiseaux/pipit.a.long.bec.html"},
    {value: 820, text: "Plongeon arctique", link: "../oiseaux/plongeon.arctique.html"},
    {value: 821, text: "Plongeon catmarin", link: "../oiseaux/plongeon.catmarin.html"},
    {value: 822, text: "Plongeon du Pacifique", link: "../oiseaux/plongeon.du.pacifique.html"},
    {value: 823, text: "Plongeon imbrin", link: "../oiseaux/plongeon.imbrin.html"},
    {value: 824, text: "Plongeon huard", link: "../oiseaux/plongeon.imbrin.html"},
    {value: 825, text: "Plongeon à bec blanc", link: "../oiseaux/plongeon.a.bec.blanc.html"},
    {value: 826, text: "Pluvian fluviatile", link: "../oiseaux/pluvian.fluviatile.html"},
    {value: 827, text: "Pluvier argenté", link: "../oiseaux/pluvier.argente.html"},
    {value: 828, text: "Pluvier asiatique", link: "../oiseaux/pluvier.asiatique.html"},
    {value: 829, text: "Pluvier bronzé", link: "../oiseaux/pluvier.bronze.html"},
    {value: 830, text: "Pluvier doré", link: "../oiseaux/pluvier.dore.html"},
    {value: 831, text: "Pluvier fauve", link: "../oiseaux/pluvier.fauve.html"},
    {value: 832, text: "Pluvier guignard", link: "../oiseaux/pluvier.guignard.html"},
    {value: 833, text: "Pouillot boréal", link: "../oiseaux/pouillot.boreal.html"},
    {value: 834, text: "Pouillot brun", link: "../oiseaux/pouillot.brun.html"},
    {value: 835, text: "Pouillot des Canaries", link: "../oiseaux/pouillot.des.canaries.html"},
    {value: 836, text: "Pouillot de Bonelli", link: "../oiseaux/pouillot.de.bonelli.html"},
    {value: 837, text: "Pouillot de Hume", link: "../oiseaux/pouillot.de.hume.html"},
    {value: 838, text: "Pouillot de Pallas", link: "../oiseaux/pouillot.de.pallas.html"},
    {value: 839, text: "Pouillot de Schwarz", link: "../oiseaux/pouillot.de.schwarz.html"},
    {value: 840, text: "Pouillot de Temminck", link: "../oiseaux/pouillot.de.temminck.html"},
    {value: 841, text: "Pouillot du Caucase", link: "../oiseaux/pouillot.du.caucase.html"},
    {value: 842, text: "Pouillot du Kamtchatka", link: "../oiseaux/pouillot.du.kamtchatka.html"},
    {value: 843, text: "Pouillot fitis", link: "../oiseaux/pouillot.fitis.html"},
    {value: 844, text: "Pouillot griséole", link: "../oiseaux/pouillot.griseole.html"},
    {value: 845, text: "Pouillot ibérique", link: "../oiseaux/pouillot.iberique.html"},
    {value: 846, text: "Pouillot modeste", link: "../oiseaux/pouillot.modeste.html"},
    {value: 847, text: "Pouillot montagnard", link: "../oiseaux/pouillot.montagnard.html"},
    {value: 848, text: "Pouillot oriental", link: "../oiseaux/pouillot.oriental.html"},
    {value: 849, text: "Pouillot siffleur", link: "../oiseaux/pouillot.siffleur.html"},
    {value: 850, text: "Pouillot verdâtre", link: "../oiseaux/pouillot.verdatre.html"},
    {value: 851, text: "Pouillot véloce", link: "../oiseaux/pouillot.veloce.html"},
    {value: 852, text: "Pouillot à deux barres", link: "../oiseaux/pouillot.a.deux.barres.html"},
    {value: 853, text: "Pouillot à grands sourcils", link: "../oiseaux/pouillot.a.grands.sourcils.html"},
    {value: 854, text: "Pouillot à gros bec", link: "../oiseaux/pouillot.a.gros.bec.html"},
    {value: 855, text: "Pouillot à pattes claires", link: "../oiseaux/pouillot.a.pattes.claires.html"},
    {value: 856, text: "Prinia gracile", link: "../oiseaux/prinia.gracile.html"},
    {value: 857, text: "Puffin boréal", link: "../oiseaux/puffin.boreal.html"},
    {value: 858, text: "Puffin cendré", link: "../oiseaux/"},
    {value: 859, text: "Puffin d'Audubon", link: "../oiseaux/puffin.d.audubon.html"},
    {value: 860, text: "Puffin des Anglais", link: "../oiseaux/puffin.des.anglais.html"},
    {value: 861, text: "Puffin des Baléares", link: "../oiseaux/puffin.des.baleares.html"},
    {value: 862, text: "Puffin de Baillon", link: "../oiseaux/puffin.de.baillon.html"},
    {value: 863, text: "Puffin de Macaronésie", link: "../oiseaux/puffin.de.macaronesie.html"},
    {value: 864, text: "Puffin de Scopoli", link: "../oiseaux/puffin.de.scopoli.html"},
    {value: 865, text: "Puffin du Cap-Vert", link: "../oiseaux/puffin.du.cap-vert.html"},
    {value: 866, text: "Puffin fuligineux", link: "../oiseaux/puffin.fuligineux.html"},
    {value: 867, text: "Puffin majeur", link: "../oiseaux/puffin.majeur.html"},
    {value: 868, text: "Puffin yelkouan", link: "../oiseaux/puffin.yelkouan.html"},
    {value: 869, text: "Puffin à bec grêle", link: "../oiseaux/puffin.a.bec.grele.html"},
    {value: 870, text: "Puffin à menton blanc", link: "../oiseaux/puffin.a.menton.blanc.html"},
    {value: 871, text: "Puffin à pieds pâles", link: "../oiseaux/puffin.a.pieds.pales.html"},
    {value: 872, text: "Pygargue de Pallas", link: "../oiseaux/pygargue.de.pallas.html"},
    {value: 873, text: "Pygargue à queue blanche", link: "../oiseaux/pygargue.a.queue.blanche.html"},
    {value: 874, text: "Pygargue à tête blanche", link: "../oiseaux/pygargue.a.tete.blanche.html"},
    {value: 875, text: "Pélican blanc", link: "../oiseaux/pelican.blanc.html"},
    {value: 876, text: "Pélican frisé", link: "../oiseaux/pelican.frise.html"},
    {value: 877, text: "Pélican gris", link: "../oiseaux/pelican.gris.html"},
    {value: 878, text: "Pétrel des Bermudes", link: "../oiseaux/petrel.des.bermudes.html"},
    {value: 879, text: "Pétrel des Kermadec", link: "../oiseaux/petrel.des.kermadec.html"},
    {value: 880, text: "Pétrel de Bulwer", link: "../oiseaux/petrel.de.bulwer.html"},
    {value: 881, text: "Pétrel de la Trinité", link: "../oiseaux/petrel.de.la.trinite.html"},
    {value: 882, text: "Pétrel de Trindade", link: "../oiseaux/"},
    {value: 883, text: "Pétrel de Madère", link: "../oiseaux/petrel.de.madere.html"},
    {value: 884, text: "Pétrel de Schlegel", link: "../oiseaux/petrel.de.schlegel.html"},
    {value: 885, text: "Pétrel diablotin", link: "../oiseaux/petrel.diablotin.html"},
    {value: 886, text: "Pétrel du désert", link: "../oiseaux/petrel.du.desert.html"},
    {value: 887, text: "Pétrel des Desertas", link: "../oiseaux/"},
    {value: 888, text: "Pétrel gongon", link: "../oiseaux/petrel.gongon.html"},
    {value: 889, text: "Pétrel géant", link: "../oiseaux/petrel.geant.html"},
    {value: 890, text: "Pétrel hérault", link: "../oiseaux/petrel.herault.html"},
    {value: 891, text: "Pétrel du Herald", link: "../oiseaux/"},
    {value: 892, text: "Pétrel noir", link: "../oiseaux/petrel.noir.html"},
    {value: 893, text: "Pétrel soyeux", link: "../oiseaux/petrel.soyeux.html"},
    {value: 894, text: "Quiscale bronzé", link: "../oiseaux/quiscale.bronze.html"},
    {value: 895, text: "Quiscale rouilleux", link: "../oiseaux/quiscale.rouilleux.html"},
    {value: 896, text: "Rhynchée peinte", link: "../oiseaux/rhynchee.peinte.html"},
    {value: 897, text: "Robin à flancs roux", link: "../oiseaux/robin.a.flancs.roux.html"},
    {value: 898, text: "Roitelet de Madère", link: "../oiseaux/roitelet.de.madere.html"},
    {value: 899, text: "Roitelet huppé", link: "../oiseaux/roitelet.huppe.html"},
    {value: 900, text: "Roitelet triple-bandeau", link: "../oiseaux/roitelet.triple-bandeau.html"},
    {value: 901, text: "Roitelet à couronne rubis", link: "../oiseaux/roitelet.a.couronne.rubis.html"},
    {value: 902, text: "Rollier d'Abyssinie", link: "../oiseaux/rollier.d.abyssinie.html"},
    {value: 903, text: "Rollier d'Europe", link: "../oiseaux/rollier.d.europe.html"},
    {value: 904, text: "Roselin cramoisi", link: "../oiseaux/roselin.cramoisi.html"},
    {value: 905, text: "Roselin de Lichtenstein", link: "../oiseaux/roselin.de.lichtenstein.html"},
    {value: 906, text: "Roselin de Mongolie", link: "../oiseaux/roselin.de.mongolie.html"},
    {value: 907, text: "Roselin familier", link: "../oiseaux/roselin.familier.html"},
    {value: 908, text: "Roselin githagine", link: "../oiseaux/roselin.githagine.html"},
    {value: 909, text: "Roselin rose", link: "../oiseaux/roselin.rose.html"},
    {value: 910, text: "Roselin tacheté", link: "../oiseaux/roselin.tachete.html"},
    {value: 911, text: "Roselin à ailes roses", link: "../oiseaux/roselin.a.ailes.roses.html"},
    {value: 912, text: "Roselin à tête grise", link: "../oiseaux/roselin.a.tete.grise.html"},
    {value: 913, text: "Rossignol bleu", link: "../oiseaux/rossignol.bleu.html"},
    {value: 914, text: "Rossignol calliope", link: "../oiseaux/rossignol.calliope.html"},
    {value: 915, text: "Rossignol philomèle", link: "../oiseaux/rossignol.philomele.html"},
    {value: 916, text: "Rossignol progné", link: "../oiseaux/rossignol.progne.html"},
    {value: 917, text: "Rossignol siffleur", link: "../oiseaux/rossignol.siffleur.html"},
    {value: 918, text: "Rougegorge familier", link: "../oiseaux/rougegorge.familier.html"},
    {value: 919, text: "Rougequeue d'Eversmann", link: "../oiseaux/rougequeue.d.eversmann.html"},
    {value: 920, text: "Rougequeue de Moussier", link: "../oiseaux/rougequeue.de.moussier.html"},
    {value: 921, text: "Rougequeue noir", link: "../oiseaux/rougequeue.noir.html"},
    {value: 922, text: "Rougequeue à front blanc", link: "../oiseaux/rougequeue.a.front.blanc.html"},
    {value: 923, text: "Rousserolle des buissons", link: "../oiseaux/rousserolle.des.buissons.html"},
    {value: 924, text: "Rousserolle effarvatte", link: "../oiseaux/rousserolle.effarvatte.html"},
    {value: 925, text: "Rousserolle isabelle", link: "../oiseaux/rousserolle.isabelle.html"},
    {value: 926, text: "Rousserolle stentor", link: "../oiseaux/rousserolle.stentor.html"},
    {value: 927, text: "Rousserolle turdoïde", link: "../oiseaux/rousserolle.turdoide.html"},
    {value: 928, text: "Rousserolle verderolle", link: "../oiseaux/rousserolle.verderolle.html"},
    {value: 929, text: "Rousserolle à gros bec", link: "../oiseaux/rousserolle.a.gros.bec.html"},
    {value: 930, text: "Râle d'eau", link: "../oiseaux/rale.d.eau.html"},
    {value: 931, text: "Râle des genêts", link: "../oiseaux/rale.des.genets.html"},
    {value: 932, text: "Râle des prés", link: "../oiseaux/rale.des.pres.html"},
    {value: 933, text: "Râle de Virginie", link: "../oiseaux/rale.de.virginie.html"},
    {value: 934, text: "Râle à bec jaune", link: "../oiseaux/rale.a.bec.jaune.html"},
    {value: 935, text: "Marouette à bec jaune", link: "../oiseaux/rale.a.bec.jaune.html"},
    {value: 936, text: "Râle à crête", link: "../oiseaux/rale.a.crete.html"},
    {value: 937, text: "Rémiz penduline", link: "../oiseaux/remiz.penduline.html"},
    {value: 938, text: "Sarcelle cannelle", link: "../oiseaux/sarcelle.cannelle.html"},
    {value: 939, text: "Sarcelle d'hiver", link: "../oiseaux/sarcelle.d.hiver.html"},
    {value: 940, text: "Sarcelle d'été", link: "../oiseaux/sarcelle.d.ete.html"},
    {value: 941, text: "Sarcelle marbrée", link: "../oiseaux/sarcelle.marbree.html"},
    {value: 942, text: "Marmaronette marbrée", link: "../oiseaux/sarcelle.marbree.html"},
    {value: 943, text: "Sarcelle à ailes bleues", link: "../oiseaux/sarcelle.a.ailes.bleues.html"},
    {value: 944, text: "Sarcelle à ailes vertes", link: "../oiseaux/sarcelle.a.ailes.vertes.html"},
    {value: 945, text: "Sarcelle élégante", link: "../oiseaux/sarcelle.elegante.html"},
    {value: 946, text: "Serin cini", link: "../oiseaux/serin.cini.html"},
    {value: 947, text: "Serin des Canaries", link: "../oiseaux/serin.des.canaries.html"},
    {value: 948, text: "Serin du Cap", link: "../oiseaux/serin.du.cap.html"},
    {value: 949, text: "Serin à front rouge", link: "../oiseaux/serin.a.front.rouge.html"},
    {value: 950, text: "Serin à front d'or", link: "../oiseaux/serin.a.front.rouge.html"},
    {value: 951, text: "Sirli de Dupont", link: "../oiseaux/sirli.de.dupont.html"},
    {value: 952, text: "Alouette de Dupont", link: "../oiseaux/"},
    {value: 953, text: "Sirli du désert", link: "../oiseaux/sirli.du.desert.html"},
    {value: 954, text: "Sittelle corse", link: "../oiseaux/sittelle.corse.html"},
    {value: 955, text: "Sittelle de Krüper", link: "../oiseaux/sittelle.de.kruper.html"},
    {value: 956, text: "Sittelle de Neumayer", link: "../oiseaux/sittelle.de.neumayer.html"},
    {value: 957, text: "Sittelle torchepot", link: "../oiseaux/sittelle.torchepot.html"},
    {value: 958, text: "Sittelle à poitrine rousse", link: "../oiseaux/sittelle.a.poitrine.rousse.html"},
    {value: 959, text: "Sizerin blanchâtre", link: "../oiseaux/sizerin.blanchatre.html"},
    {value: 960, text: "Sizerin cabaret", link: "../oiseaux/sizerin.cabaret.html"},
    {value: 961, text: "Sizerin flammé", link: "../oiseaux/sizerin.flamme.html"},
    {value: 962, text: "Spatule blanche", link: "../oiseaux/spatule.blanche.html"},
    {value: 963, text: "Spatule d'Afrique", link: "../oiseaux/spatule.d.afrique.html"},
    {value: 964, text: "Starique cristatelle", link: "../oiseaux/starique.cristatelle.html"},
    {value: 965, text: "Starique perroquet", link: "../oiseaux/starique.perroquet.html"},
    {value: 966, text: "Sterne arctique", link: "../oiseaux/sterne.arctique.html"},
    {value: 967, text: "Sterne bridée", link: "../oiseaux/sterne.bridee.html"},
    {value: 968, text: "Sterne caspienne", link: "../oiseaux/sterne.caspienne.html"},
    {value: 969, text: "Sterne caugek", link: "../oiseaux/sterne.caugek.html"},
    {value: 970, text: "Sterne des Aléoutiennes", link: "../oiseaux/sterne.des.aleoutiennes.html"},
    {value: 971, text: "Sterne de Cabot", link: "../oiseaux/sterne.de.cabot.html"},
    {value: 972, text: "Sterne de Dougall", link: "../oiseaux/sterne.de.dougall.html"},
    {value: 973, text: "Sterne de Forster", link: "../oiseaux/sterne.de.forster.html"},
    {value: 974, text: "Sterne de Saunders", link: "../oiseaux/sterne.de.saunders.html"},
    {value: 975, text: "Sterne fuligineuse", link: "../oiseaux/sterne.fuligineuse.html"},
    {value: 976, text: "Sterne hansel", link: "../oiseaux/sterne.hansel.html"},
    {value: 977, text: "Sterne naine", link: "../oiseaux/sterne.naine.html"},
    {value: 978, text: "Sterne pierregarin", link: "../oiseaux/sterne.pierregarin.html"},
    {value: 979, text: "Sterne royale", link: "../oiseaux/sterne.royale.html"},
    {value: 980, text: "Sterne voyageuse", link: "../oiseaux/sterne.voyageuse.html"},
    {value: 981, text: "Sterne à dos pâle", link: "../oiseaux/sterne.a.dos.pale.html"},
    {value: 982, text: "Sterne royale (Afrique)", link: "../oiseaux/"},
    {value: 983, text: "Sterne à joues blanches", link: "../oiseaux/sterne.a.joues.blanches.html"},
    {value: 984, text: "Sterne élégante", link: "../oiseaux/sterne.elegante.html"},
    {value: 985, text: "Syrrhapte paradoxal", link: "../oiseaux/syrrhapte.paradoxal.html"},
    {value: 986, text: "Tadorne casarca", link: "../oiseaux/tadorne.casarca.html"},
    {value: 987, text: "Tadorne de Belon", link: "../oiseaux/tadorne.de.belon.html"},
    {value: 988, text: "Talève d'Afrique", link: "../oiseaux/taleve.d.afrique.html"},
    {value: 989, text: "Talève d'Allen", link: "../oiseaux/taleve.d.allen.html"},
    {value: 990, text: "Talève sultane", link: "../oiseaux/taleve.sultane.html"},
    {value: 991, text: "Talève violacée", link: "../oiseaux/taleve.violacee.html"},
    {value: 992, text: "Talève à tête grise", link: "../oiseaux/taleve.a.tete.grise.html"},
    {value: 993, text: "Tangara vermillon", link: "../oiseaux/tangara.vermillon.html"},
    {value: 994, text: "Piranga vermillon", link: "../oiseaux/"},
    {value: 995, text: "Tangara écarlate", link: "../oiseaux/tangara.ecarlate.html"},
    {value: 996, text: "Piranga écarlate", link: "../oiseaux/"},
    {value: 997, text: "Tantale ibis", link: "../oiseaux/tantale.ibis.html"},
    {value: 998, text: "Tarier africain", link: "../oiseaux/tarier.africain.html"},
    {value: 999, text: "Tarier d'Afrique", link: "../oiseaux/"},
    {value: 1000, text: "Tarier des Canaries", link: "../oiseaux/tarier.des.canaries.html"},
    {value: 1001, text: "Tarier des prés", link: "../oiseaux/tarier.des.pres.html"},
    {value: 1002, text: "Tarier de Sibérie", link: "../oiseaux/tarier.de.siberie.html"},
    {value: 1003, text: "Tarier de Stejneger", link: "../oiseaux/tarier.de.stejneger.html"},
    {value: 1004, text: "Tarier pie", link: "../oiseaux/tarier.pie.html"},
    {value: 1005, text: "Tarier pâtre", link: "../oiseaux/tarier.patre.html"},
    {value: 1006, text: "Tarin des aulnes", link: "../oiseaux/tarin.des.aulnes.html"},
    {value: 1007, text: "Tchagra à tête noire", link: "../oiseaux/tchagra.a.tete.noire.html"},
    {value: 1008, text: "Tichodrome échelette", link: "../oiseaux/tichodrome.echelette.html"},
    {value: 1009, text: "Tisserin gendarme", link: "../oiseaux/tisserin.gendarme.html"},
    {value: 1010, text: "Tisserin à tête noire", link: "../oiseaux/tisserin.a.tete.noire.html"},
    {value: 1011, text: "Tohi à flancs roux", link: "../oiseaux/tohi.a.flancs.roux.html"},
    {value: 1012, text: "Torcol fourmilier", link: "../oiseaux/torcol.fourmilier.html"},
    {value: 1013, text: "Torrentaire à calotte blanche", link: "../oiseaux/torrentaire.a.calotte.blanche.html"},
    {value: 1014, text: "Rougequeue à calotte blanche", link: "../oiseaux/torrentaire.a.calotte.blanche.html"},
    {value: 1015, text: "Tournepierre à collier", link: "../oiseaux/tournepierre.a.collier.html"},
    {value: 1016, text: "Tourterelle des bois", link: "../oiseaux/tourterelle.des.bois.html"},
    {value: 1017, text: "Tourterelle maillée", link: "../oiseaux/tourterelle.maillee.html"},
    {value: 1018, text: "Tourterelle masquée", link: "../oiseaux/tourterelle.masquee.html"},
    {value: 1019, text: "Tourtelette masquée", link: "../oiseaux/tourterelle.masquee.html"},
    {value: 1020, text: "Tourterelle orientale", link: "../oiseaux/tourterelle.orientale.html"},
    {value: 1021, text: "Tourterelle rieuse", link: "../oiseaux/tourterelle.rieuse.html"},
    {value: 1022, text: "Tourterelle triste", link: "../oiseaux/tourterelle.triste.html"},
    {value: 1023, text: "Tourterelle turque", link: "../oiseaux/tourterelle.turque.html"},
    {value: 1024, text: "Tourterelle à queue carrée", link: "../oiseaux/tourterelle.a.queue.carree.html"},
    {value: 1025, text: "Traquet deuil", link: "../oiseaux/traquet.deuil.html"},
    {value: 1026, text: "Traquet de Chypre", link: "../oiseaux/traquet.de.chypre.html"},
    {value: 1027, text: "Traquet de Finsch", link: "../oiseaux/traquet.de.finsch.html"},
    {value: 1028, text: "Traquet de Seebohm", link: "../oiseaux/traquet.de.seebohm.html"},
    {value: 1029, text: "Traquet du désert", link: "../oiseaux/traquet.du.desert.html"},
    {value: 1030, text: "Traquet isabelle", link: "../oiseaux/traquet.isabelle.html"},
    {value: 1031, text: "Traquet kurde", link: "../oiseaux/traquet.kurde.html"},
    {value: 1032, text: "Traquet motteux", link: "../oiseaux/traquet.motteux.html"},
    {value: 1033, text: "Traquet noir et blanc", link: "../oiseaux/traquet.noir.et.blanc.html"},
    {value: 1034, text: "Traquet oreillard", link: "../oiseaux/traquet.oreillard.html"},
    {value: 1035, text: "Traquet pie", link: "../oiseaux/traquet.pie.html"},
    {value: 1036, text: "Traquet rieur", link: "../oiseaux/traquet.rieur.html"},
    {value: 1037, text: "Traquet variable", link: "../oiseaux/traquet.variable.html"},
    {value: 1038, text: "Traquet à capuchon", link: "../oiseaux/traquet.a.capuchon.html"},
    {value: 1039, text: "Traquet à tête blanche", link: "../oiseaux/traquet.a.tete.blanche.html"},
    {value: 1040, text: "Traquet à tête grise", link: "../oiseaux/traquet.a.tete.grise.html"},
    {value: 1041, text: "Troglodyte des marais", link: "../oiseaux/troglodyte.des.marais.html"},
    {value: 1042, text: "Troglodyte mignon", link: "../oiseaux/troglodyte.mignon.html"},
    {value: 1043, text: "Turnix mugissant", link: "../oiseaux/turnix.mugissant.html"},
    {value: 1044, text: "Turnix d'Andalousie", link: "../oiseaux/turnix.mugissant.html"},
    {value: 1045, text: "Tyran des savanes", link: "../oiseaux/tyran.des.savanes.html"},
    {value: 1046, text: "Tyran de l'Ouest", link: "../oiseaux/tyran.de.l.ouest.html"},
    {value: 1047, text: "Tyran tritri", link: "../oiseaux/tyran.tritri.html"},
    {value: 1048, text: "Tétras lyre", link: "../oiseaux/tetras.lyre.html"},
    {value: 1049, text: "Vacher à tête brune", link: "../oiseaux/vacher.a.tete.brune.html"},
    {value: 1050, text: "Vanneau huppé", link: "../oiseaux/vanneau.huppe.html"},
    {value: 1051, text: "Vanneau indien", link: "../oiseaux/vanneau.indien.html"},
    {value: 1052, text: "Vanneau sociable", link: "../oiseaux/vanneau.sociable.html"},
    {value: 1053, text: "Vanneau à queue blanche", link: "../oiseaux/vanneau.a.queue.blanche.html"},
    {value: 1054, text: "Vanneau à tête grise", link: "../oiseaux/vanneau.a.tete.grise.html"},
    {value: 1055, text: "Vanneau éperonné", link: "../oiseaux/vanneau.eperonne.html"},
    {value: 1056, text: "Vanneau à éperons", link: "../oiseaux/vanneau.eperonne.html"},
    {value: 1057, text: "Vautour africain", link: "../oiseaux/vautour.africain.html"},
    {value: 1058, text: "Vautour de Rüppell", link: "../oiseaux/vautour.de.ruppell.html"},
    {value: 1059, text: "Vautour fauve", link: "../oiseaux/vautour.fauve.html"},
    {value: 1060, text: "Vautour moine", link: "../oiseaux/vautour.moine.html"},
    {value: 1061, text: "Vautour oricou", link: "../oiseaux/vautour.oricou.html"},
    {value: 1062, text: "Venturon corse", link: "../oiseaux/venturon.corse.html"},
    {value: 1063, text: "Venturon montagnard", link: "../oiseaux/venturon.montagnard.html"},
    {value: 1064, text: "Verdier d'Europe", link: "../oiseaux/verdier.d.europe.html"},
    {value: 1065, text: "Viréo aux yeux blancs", link: "../oiseaux/vireo.aux.yeux.blancs.html"},
    {value: 1066, text: "Viréo de Philadelphie", link: "../oiseaux/vireo.de.philadelphie.html"},
    {value: 1067, text: "Viréo mélodieux", link: "../oiseaux/vireo.melodieux.html"},
    {value: 1068, text: "Viréo à gorge jaune", link: "../oiseaux/vireo.a.gorge.jaune.html"},
    {value: 1069, text: "Viréo à oeil rouge", link: "../oiseaux/vireo.a.oeil.rouge.html"},
    {value: 1070, text: "Viréo aux yeux rouges", link: "../oiseaux/"},
    {value: 1071, text: "Viréo à tête bleue", link: "../oiseaux/vireo.a.tete.bleue.html"},
    {value: 1072, text: "Échasse blanche", link: "../oiseaux/echasse.blanche.html"},
    {value: 1073, text: "Élanion blanc", link: "../oiseaux/elanion.blanc.html"},
    {value: 1074, text: "Épervier d'Europe", link: "../oiseaux/epervier.d.europe.html"},
    {value: 1075, text: "Épervier à pieds courts", link: "../oiseaux/epervier.a.pieds.courts.html"},
    {value: 1076, text: "Érismature rousse", link: "../oiseaux/erismature.rousse.html"},
    {value: 1077, text: "Érismature à tête blanche", link: "../oiseaux/erismature.a.tete.blanche.html"},
    {value: 1078, text: "Étourneau de Daourie", link: "../oiseaux/etourneau.de.daourie.html"},
    {value: 1079, text: "Étourneau roselin", link: "../oiseaux/etourneau.roselin.html"},
    {value: 1080, text: "Étourneau sansonnet", link: "../oiseaux/etourneau.sansonnet.html"},
    {value: 1081, text: "Étourneau unicolore", link: "../oiseaux/etourneau.unicolore.html"}
], ['text'], ['asc'])
